### ISSUE TITLE
Delayed Bookmark Response

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1012]
I am using Galaxy Note 10.

Creating/deleting bookmark function is not working properly. In highlighting text, then clicking bookmark, no text shows as highlighted. In trying to delete a bookmark, the highlighted text remains highlighted. 

I have noticed that if you leave the location at which you are trying to create/delete a specific bookmark & come back to it, it will show as highlighted text, or show that it has been deleted.

Thanks, 

Debra

**Comment by agrogers** [comment]
Hi. I have had this too. Some more info that might be helpful:
* closing and reopening the app solves the problem.... for a while
* sometimes the speed varies - slow then it seems fast then slow again
* the app is usually fully responsive while i am waiting for the bookmark to add. Seems like the bookmark adding is running in a different thread from the main app.
* it regularly gets slower the more bookmarks i add. It seems proportionate. However when i come back after a restart it seems fine.

What happens when it is really slow.
https://drive.google.com/file/d/1ZGlgZL_KgWVRLQgPhfzFWdZziKoFaFr6/view?usp=sharing

**Comment by tuomas2** [comment]
I believe this is now fixed.
