### ISSUE TITLE
Create a setting to pick bibles in compare... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1049]
When comparing verse(s) it would be nice to be able to select which bibles you want in the compare window. 

Currently all bibles are included in the compare function.

In the application settings create an item where you could pick which bibles to be listed when comparing.

**Comment by tuomas2** [comment]
@agrogers you could think about where and how this would be best implemented

**Comment by agrogers** [comment]
Here are my first thoughts on a filter for this area. I don't feel like it needs a separate menu item in settings somewhere. It would work nicely in the compare window itself.

![AndBible Suggestions-compare verses](https://user-images.githubusercontent.com/13920678/118359903-ce0d5900-b5c8-11eb-91cc-f0c428723076.png)

**Comment by timbze** [comment]
To add to @agrogers nice idea, it would be helpful for me to be able to set the order. For example, I wanted NASB first, then ESV, then NET, etc

**Comment by timbze** [comment]
Also, I like the idea to place the filter icon at this place. However, I have also thought of having a few more window specific options in a similar way in the future, for example,
- Open all references opens 10 verses, and then I would like to be able to switch them all to another Bible version.
- Also for windows like open all references, compare, study pad, to have an export option... This place would also be a good option for that.

When you scroll down it would disappear because it would just be placed at that location in the webview

**Comment by agrogers** [comment]
I would tend to think an Export option should go on the Window button.

Switching versions is an interesting idea.

I agree that the top row is a good place for other potential actions. Ordering is one that is in my mind but I think there is more to these lists than meets the eye so ordering might be messy or impossible.

**Comment by bvahedy** [comment]
I'm thinking it should be at the workspace level not at Bible window level. So each workspace can have it's own compare list. Any thoughts?

**Comment by tuomas2** [comment]
"filter is saved on workspace level" in @agrogers 's specs

**Comment by bvahedy** [comment]
Ok, I see it now. I thought since the filter was displaying on the compare window that it was on the current Bible window. can the filter be placed on the workspace list page, since it's more of a setting. Otherwise you would have to invoke the compare to get to the filter.

**Comment by agrogers** [comment]
A few thoughts:

* Definitely agree that it should (also) be included in the workspace settings. Good point.
* I see Settings as something that a user sets once then mostly forgets. For example, night mode or font size.
* How often would we want to change this setting? If it might get changed more than a few times then I think it justifies being accessible from the
interface where it is being used.
* Can we include the button in the compare window without it making the interface messy or confusing?

I feel at the moment that the answers to those questions encourages having the icon in the compare window itself and accessible in the workspace settings.

As an aside
* I am still stumbling on to settings I didn't realise were there or I had forgotten about. This is kind of a problem because an unused feature is a missed opportunity to help/impress/secure a user. Or we wasted our time developing it.
* I had an aversion to using the 'auto assign labels' setting via the 'Text options' because it just wasn't part of the label assigning workflow. It wasn't that it took that much longer. It was that it felt like a detour from what I was trying to do. I don't like detours.
* And Bible functionality has grown so much that it is getting harder for a user to discover what it can do. Or worse - it might confuse the user.

**Comment by bvahedy** [comment]
You make a good point, if it is in the workspace settings only then new users may never know it's there. If it doesn't clutter up the compare window, it would be nice to have it there also. 

This brings up another point which I've been thinking about for the last three years. It would be nice if we could  create small screen recordings of different functionalities of Andbible and place them somewhere on the wiki page or somewhere else and put the link to that in the Google playstore's app description. right now there are so many changes taking place that the recordings may be outdated by the time we place it there.
 Something to think about for another the years🙄.

**Comment by agrogers** [comment]
I added a feature here which is kind of related to your last comment #1071

Having as much help in the app as possible is usually my preference. I think screen recordings are good too. Even just a 5 frame gif would often convey the ideas better than a long blurb. Making it available outside the app would also be good.

**Comment by tuomas2** [comment]
Implemented in 602956ac64841891774adf242dd5841257ab9678 but bit different UI
