### ISSUE TITLE
Underline highlight

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1082]
> Implemented otherwise, but not underline style.

Hi Tumoas. I think by 'implemented' you mean just using the current method. That's ok. But I think it can be better :)

> We can't have multiple underlines using CSS.

It's possible although it might make your code a little harder to manage. Below is what I could come up with and attached it the code I used/stole to do it.
[special_underline.html](https://github.com/AndBible/and-bible/files/6520999/special_underline.html.txt)

Again, the reason I like this approach is because:
1. I find reading a passage when the whole verse is highlighted to be a little uncomfortable. The highlight is too dominant and i feel like it breaks my focus.
2. The highlights that I really want to see clearly are the single word/phrase highlights. When the whole line is highlighted these words are then highlighted with a half height. So now the verse highlight is taking over the word highlighting. It gets worse if that word is highlighted again in a larger piece of text. Now it is down to a third height.
3. Often i want to indicate that a whole section - say five verses or more - is about a particular topic and then pick out particular words or phrases that are important to me. 
4. But I avoid highlighting whole verses because I personally don't want the verse/ passage/ chapter to be all yellow :) If i want that much color i can change the window background color ;-)

Perhaps the ultimate solution for me would be to be able to specify the type of highlight - background or underline - with whole verses by default being underlined and phrases being background highlighted. If this became possible it would mean that my old paper bible highlighting method is now completely possible in And Bible :D  

![image](https://user-images.githubusercontent.com/13920678/119101057-ef07fb00-ba5b-11eb-8c3e-50cb027f2bbe.png)

_Originally posted by @agrogers in https://github.com/AndBible/and-bible/issues/1017#issuecomment-845740097_

**Comment by tuomas2** [comment]
> Hi Tumoas. I think by 'implemented' you mean just using the current method. That's ok. But I think it can be better :)

I mean I implemented everything else.

Thank you for example code. If it would be possible to be done with a single-statement css it would be easier to implement. 

I agree with your rationale, but am hesitating if I want to implement this, at least for now.

**Comment by agrogers** [comment]
Yeah, I thought that css would be a lot more complicated. Personally I would be perfectly happy with a single underline using whatever whole-verse bookmark color. If I don't like the color I could change to the current arrangement of selecting the text I want highlighted and thus get the colors I want as the background color.

**Comment by tuomas2** [comment]
Maybe we could have single underline, and if there are two or more overlapping bookmarks with underline style, it would double-underline (or wavy underline, or some other css text-decoration style) with generic color (for example coming from 'unlabelled' bookmark style) hiding the label coloring data.

**Comment by agrogers** [comment]
I like it. Single underline, double underline and wavy underline could represent 1,2 and 3 whole verse bookmarks. I think I would personally stick with the color of one of the bookmarks - perhaps the first added. The color is important and losing that would be a shame. And there is a precedent I think - the little bookmark symbol that appears at the end of a verse to indicate bookmarks on that verse in other translations is a single color.

I think I might even prefer the dotted underline rather than the solid underline. But that might mess with the strong number underline highlighting... oh, that complicates things again 😕 I can see you might not want to go down this rabbit warren!

**Comment by tuomas2** [comment]
first or last added makes sense. I might think that last added is more logical, what do you think?

**Comment by agrogers** [comment]
Hmmm, i think first for me. It means i could configure it (remove all and re-add in the correct order) such that it didnt change color with subsequent bookmarks. But I would probably be aiming for only one whole verse underline so it wouldnt matter so much.

**Comment by tuomas2** [comment]
data structure and label editing done in 5ed72eee3c78a159b47b9685bee147eabb2c6eb0

**Comment by tuomas2** [comment]
Actual implementation (showing underlines) not yet implemented. Implementing it later.

**Comment by tuomas2** [comment]
It will look like this

![image](https://user-images.githubusercontent.com/5811789/119850865-97afd200-bf16-11eb-9517-9a7ed9be14cb.png)

(hiding checkboxes for now)

**Comment by tuomas2** [comment]
Implemented rest in 31f4b067f7de1d9639c1b681db5ac4410f3ebca6

**Comment by tuomas2** [comment]
Included in build 524.3

**Comment by agrogers** [comment]
Good work Tuomas. I didn't see your comment with screenshot from a few days ago until just now. Only suggestions that came to mind when i tested it just now was:

- [x] 1. The underline looks to be using the paler background color rather than the actual label color which is stronger. I think the underline is probably fine with the actual label color and maybe needed for some colors because the underline is too faint to be easily seen.
- [x] 2. Is there a reason you put the checkboxes on the left side, not the right side where checkboxes are normally located in AndBible
- [x] 3. And the vertical alignment between label and checkbox is not centered - I like centered :)

Thanks again for this! Hopefully people appreciate it as much as I do.

**Comment by tuomas2** [comment]
Re-opening for the fixes.
(please re-open tickets if you add some tasks or something waiting for my response etc there, so they don't get forgotten :-) )

**Comment by agrogers** [comment]
> (please re-open tickets if you add some tasks or something waiting for my response etc there, so they don't get forgotten :-) )
Sure thing. Wasn't sure what the correct etiquette was for this.

**Comment by tuomas2** [comment]
Moved icons to left side so that text can flow to 2 lines if needed (depends on device and language). (could be done otherwise, but this was simpler)
