### ISSUE TITLE
Enhancement to 'Quick Label Assignment' dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1104]
Good work on the new label dialog Tuomas. Here are a few thoughts for you...
![AndBible Suggestions label assign dialog](https://user-images.githubusercontent.com/13920678/120058647-c7ceb080-c08f-11eb-96f0-aa96a24982f8.png)

- It would be good to maintain consistency between all our menus and dialogs. No.4 image is an example. It has teal color headings in a small font and gray icons. I like the gray icons. I don't mind the small headings. I think we can use that style in this dialog.
- We need the same vertical spacing between labels as we have horizontal spacing (approx 3px).
- The white text on gray background is hard to read. Also, i think the gray background makes the unselected labels a little too dominant. I think I still prefer a colored border (maybe thinner that you have) with black or dark gray text on white background 
- I feel the 'Current labels' heading is unhelpful. It makes it feel like the labels underneath it should act like all the others labels on the dialog. And although it literally spells out which labels are assigned to this bookmark, it kind of feels less clear to me
- My proposal is to change the dialog title to 'Bookmark labels' which can essentially replace the 'Current labels' heading
- Adding a line to separate the current labels from the other label buttons makes it even clearer to me. This follows the settings style shown in No.4 
- There might also be a case for making the assigned labels above the line slightly more dominant - maybe a little larger or in bold print. 
- The biggest change I would suggest is to eliminate duplicate labels. No.2 shows how it is possible to end up with every label shown three (or four) times. In No.3 the unselected labels are shown multiple times also. Ironically, even showing the current labels highlighted three times as in No.3 tends to make things less clear to me. It is probably a case where unnecessary information muddies the waters. I expect to see just the 1 label I have added stand out clearly. In No.3 it seems like I have added the 3 labels :)
- The logic I would use is simply don't show a label that has already been displayed. So, Current labels take precedence over Favourite labels which takes precedence over Recent labels which takes precedence over Frequently used labels if that is implemented
- Maybe a long press on an assigned label could be added to allow the user to remove a label or make it the primary label. Hmm, setting a primary label is only applicable when there is more than one label. So perhaps clicking an assigned label removes it, long clicking shows a menu with the following options perhaps (Remove label, Make Primary, Edit [which would go straight to the label dialog to change the color or something], Study Pad)
- I think the recent labels are limited to 5. I would personally like more than that - 10, 20 even.

**Comment by tuomas2** [comment]
> It would be good to maintain consistency between all our menus and dialogs. No.4 image is an example. It has teal color headings in a small font and gray icons. I like the gray icons. I don't mind the small headings. I think we can use that style in this dialog.

Two different styles come from the fact that we are dealing with Android native code and JS code. JS side could try to mimick the Android native side, but how Android native side looks, varies based on what android version etc you are using, so it would not be 100% consistent. 

- [x] > We need the same vertical spacing between labels as we have horizontal spacing (approx 3px).
- [x] > The white text on gray background is hard to read. Also, i think the gray background makes the unselected labels a little 

too dominant. I think I still prefer a colored border (maybe thinner that you have) with black or dark gray text on white background

This choise is easy because it works directly with day & night mode. I'll try something still. 

- [x] > I feel the 'Current labels' heading is unhelpful. It makes it feel like the labels underneath it should act like all the others labels on the dialog. And although it literally spells out which labels are assigned to this bookmark, it kind of feels less clear to me
- [x] > My proposal is to change the dialog title to 'Bookmark labels' which can essentially replace the 'Current labels' heading
- [x] > Adding a line to separate the current labels from the other label buttons makes it even clearer to me. This follows the settings style shown in No.4
- [ ] > There might also be a case for making the assigned labels above the line slightly more dominant - maybe a little larger or in bold print.
- [x] > The biggest change I would suggest is to eliminate duplicate labels. No.2 shows how it is possible to end up with every label shown three (or four) times. In No.3 the unselected labels are shown multiple times also. Ironically, even showing the current labels highlighted three times as in No.3 tends to make things less clear to me. It is probably a case where unnecessary information muddies the waters. I expect to see just the 1 label I have added stand out clearly. In No.3 it seems like I have added the 3 labels :) The logic I would use is simply don't show a label that has already been displayed. So, Current labels take precedence over Favourite labels which takes precedence over Recent labels which takes precedence over Frequently used labels if that is implemented
- [ ] > Maybe a long press on an assigned label could be added to allow the user to remove a label or make it the primary label. Hmm, setting a primary label is only applicable when there is more than one label. So perhaps clicking an assigned label removes it, long clicking shows a menu with the following options perhaps (Remove label, Make Primary, Edit [which would go straight to the label dialog to change the color or something], Study Pad)
- [x] > I think the recent labels are limited to 5. I would personally like more than that - 10, 20 even.

**Comment by tuomas2** [comment]
Hmm I think this is now "good enough" to my taste, so closing :-) Thanks again for ideas!
