### ISSUE TITLE
Default bookmarks & labels

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1172]
> 5. A set of labels. Perhaps those labels can be called 'Blue', 'Red',' Green' etc. So when a user goes to add a bookmark there are already a number of labels they can choose from - they dont have to create any.
> 6. Maybe some labels already assigned - perhaps to Genesis 1:1 so that the study pad functionality can be used.

- [ ] these we could implement in 3.4. As an example of topical label there could be "Salvation" topic and few bookmarks in it.

So new default labels
- Red
- Green
- Blue
- Underline
- Salvation

Feel free to suggest verses to be bookmarked with label "Salvation" (in addition to Joh 3:16)

**Comment by tuomas2** [comment]
Feel free to suggest verses to be bookmarked with label "Salvation" (in addition to Joh 3:16)

**Comment by timbze** [comment]
Some possibilities (you can pick and choose)
Salvation
- John 3:3
- Titus 3:3-7 (too long?)
- Romans 3:23-24
- Romans 4:3
- 1Tim 1:15
- Eph 2:8-9

**Comment by agrogers** [comment]
I would not add a label to too many more verses than this because the bookmarks can only be removed one by one. Although I imagine not too many people would disagree with this label choice, I still wouldnt want to make it too difficult for them to remove what we have forced on to them.

My reason for proposing some default labels was to try and reduce the barriers to highlighting a verse in some particular color. I think this is especially important for new users. 

What I noticed in YouVersion (and others apps) was you could do this by:
1. Click once on a verse.
2. Choose your color (from a list of 14 colors). Verse is now highlighted.

In And Bible (without existing labels) the process is:
1. Long click on the verse to select a word (not so intuitive for a user)
2. Choose 'Bookmark'
3. Choose 'Verses'
4. Click again on the verse which now has a default highlight (not so intuitive)
5. Click on the Unlabelled label (not so intuitive)
6. Click 'Select or edit labels...' button
7. Click the plus button to add a label
8. Enter the details of the label (with lots of possible options which might be a bit scary for a new user)
9. Click back
10. Click back 
11. Close the bookmark labels dialog
12. Now you can see your highlighted verse.

With some preexisting, default colored labels already set up AND already added to the Recent Labels list (or Favourite list) we can reduce the number of steps to 6. I still think that is too many steps, especially for users coming from other apps.

That is why I proposed 
- #1105 (eliminates steps 4 and 5 - steps I go through for almost every bookmark I add)
- #1162 (eliminates steps 1-5). This proposal also brings all the common functionality to the forefront.
- And this issue (eliminates steps 6-11)

If all of those were implemented a new user could highlight a single verse in 2 steps without losing any of the bookmarking power that And Bible already has.  In fact, those proposals are for the most part not adding new features - they are simply getting to existing functionality in a much more direct manner.

**Comment by tuomas2** [comment]
> Some possibilities (you can pick and choose)
> Salvation
> 
> * John 3:3
> * Titus 3:3-7 (too long?)
> * Romans 3:23-24
> * Romans 4:3
> * 1Tim 1:15
> * Eph 2:8-9

I guess I must add also Gen.1.1 and Joh.3.16 because those are the possible landing pages. Joh 3.16 is default if downloaded bible has NT. Gen.1.1 is otherwise.

**Comment by agrogers** [comment]
10 commandments perhaps? I know some of us like Ray Comfort.
Is 6:3 - the most important verse in the Bible (according to me)
Rev 4:8 - second most important verse :-)

Whatever verses we choose, having the bible open to one of them would be good. 

But again, bookmarks can only be deleted one by one. As long as we are ok with the implications of that.

**Comment by tuomas2** [comment]
Bit weird that they all will go under label "salvation", but we can't do much about it at this point :-P

**Comment by tuomas2** [comment]
Partly implemented in 8a831e2da38e5b883255243cd2d1b5198495a41e

**Comment by agrogers** [comment]
Were you adding some other default labels like 'Red' and 'Yellow' etc? If so you could place some under those.  Surely colors I could translate myself via Google Translate?

**Comment by tuomas2** [comment]
red, green and blue, underline. I think they are a good start for a new user.

**Comment by timbze** [comment]
I don't think the migration should happen for existing users. Except maybe if they have no bookmarks or labels yet? 

Trying to put myself in current user's shoes I think it feels intrusive to be upgraded with bookmarks when I already have bookmarks

**Comment by agrogers** [comment]
Yeah, I thought it would only be for new users. But possibly good for users
with no labels at all.

**Comment by tuomas2** [comment]
I see. I also ended up removing them...

**Comment by tuomas2** [comment]
Because of bug fixed in last commit, you now have one ridiculously long bookmark spanning from exodus chapter 2 to chapter 17. :-D It's cool to notice that AB still performs pretty fast even when handling that bookmark.

**Comment by agrogers** [comment]
Awesome. I am impressed how well it handles a lot of html markup. All of
Romans can be done :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I think this is now fully implemented.

**Comment by agrogers** [comment]
How does it work? A new install gets predefined labels and bookmarks?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
```
if no manually created labels exist in db,
   create highlight and salvation labels. 
    if no bookmarks are created in db, 
        create example bookmarks too. 
if there exists workspaces
   mark created highlight labels as favourite in all of them (if created labels)
else
   create 2 workspaces with highlight labels as favourite 

```

**Comment by agrogers** [comment]
Sounds good to me. Are there some examples of two bookmarks on the one
verse? And are the labels both underline and normal style? It would be
great to demonstrate the highlighting of a particular word but that can
only be done if we know the version.

Just desiring to give an example of as much as possible.

**Comment by tuomas2** [comment]
> Are there some examples of two bookmarks on the one verse? And are the labels both underline and normal style? It would be great to demonstrate the highlighting of a particular word but that can only be done if we know the version.

No... I'll re-open and see this again. We could highlight some random words maybe in landing verses.

**Comment by agrogers** [comment]
Oh yeah, random words could work. And the same word multiple times. They
are two features no one else has.

Well done again on all the work you are doing. I am looking forward to
getting some videos together to really show it off.

**Comment by tuomas2** [comment]
I think only thing pending for videos is icons :-)

**Comment by agrogers** [comment]
And a lot of thinking 🤔
Back to the icons tomorrow. Should have all of them by Sunday. Then we can
tweak the ones we don't like.

**Comment by tuomas2** [comment]
Looks now like this: 

![Screenshot_20210722_163145](https://user-images.githubusercontent.com/5811789/126647343-3be9c3b8-7b11-4a98-943f-fa6004e34729.png)

**Comment by agrogers** [comment]
Great
