### ISSUE TITLE
"Assign labels" screen needs more information / help

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1179]
There are 4 icons in a selected label that can be toggled. It's a bit hard to remember (also learn) what they all are for.

My suggestion is either to:
* Show a non-scroll section above "Selected labels" with the 4 lines of what the icons do, like this:
  * [label icon] Auto-assign in this workspace (line 1)
  * [heart icon] Favorite label
  * [check icon] Selected for John 3:16 [show the current bookmark info (or, see point 2 below)]
  * [bookmark icon] Default label for this bookmark

Or
* Show the info in each line as the options are toggled, for example:
  * Toggle label selected to on -> the view height for the label increases to show (line 1 above) under the current selected row
  * Toggle any of the other options -> show that particular info in the label view

2. Possibly, also show the current bookmark info centered at the top (under toolbar)

**Screenshot**
![image](https://user-images.githubusercontent.com/35117769/123338348-ea74ad80-d505-11eb-8ec6-64eaf254cc41.png)

**Comment by tuomas2** [comment]
@agrogers what do you think?

**Comment by tuomas2** [comment]
Do we need new strings? If we do, what exactly?

**Comment by agrogers** [comment]
I was sure I responded to this first thing this morning. A few comments:

1. I agree that there are a lot of check box controls on this grid. In fact...
2. New users are unlikely to know they are even controls. I am ok with that because...
3. All the functionality that the controls in the list provide are accessible from the Edit dialog.
4. In the Edit dialog the icon is attached to the description of what the icon does. This was intentional to try and educate the user as to what each icon refers to. Perhaps those descriptions could be better or more detailed?
5. Having a Help icon at the top with explanations about how this form works would be good
6. I would be reluctant to add any more fixed rows at the top on mobile devices due to small screen size
7. But a single row (not fixed) at the top with Icon description would be fine. A little weird perhaps. I think next point would be better.
7. What could be good is a section at the top - like a tool tip - that explains what is going on. That section could be dismissed by the user. So it does what Tim suggested only it is not fixed forever. That could be a good alternative/addition to #1071 
8. Maybe showing a Toast message when something is selected or deselected... but i dont feel it is necessary personally - they can remind themselves what the icons do just by editing the label.
9. Cosmetically, i might  remove some of the white space between the icons.
Have I missed something?

**Comment by tuomas2** [comment]
I think this is fixed now sufficiently
