### ISSUE TITLE
English (only) app name change for 4.0

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1235]
Presently we seem to have
- And Bible
- Bible Study

I am not sure the reason behind having one title in the play store and another on the device. 

I would like to propose:
- The Study Bible

But that longer form would only show 'The Study' on my phone home screen. So 'Study Bible' might be a better option.

Then we have the persecuted regions. Do we propose an innocuous title for those installs?
- The Book
- Study

I think we will need to use this in any promotional or training videos.

**Comment by tuomas2** [comment]
There are 3 official versions of the name: short, medium and long. 

They are: 
```
<string name="app_name_short">Bible Study</string>
    <string name="app_name_medium">Bible Study (And Bible)</string>
    <string name="app_name_long">Bible Study app, by And Bible Open Source Project</string>
```
We can make changes to these in english (via transifex / en_gb) in 4.0 if we want to, but not globally. 

Reasons for the current name(s) are:
- we want to keep "and bible" 
- we want to show that we are open source project, making this whole lot different approach from other apps
- we want to tell the purpose of the app, i.e. bible study. 

So you would propose the following changes:

```
<string name="app_name_short">The Study Bible</string>
    <string name="app_name_medium">The Study Bible (And Bible)</string>
    <string name="app_name_long">The Study Bible app, by And Bible Open Source Project</string>
```
?

**Comment by tuomas2** [comment]
For background: we changed the name in 3.3and there was discussion preceding the change. I guess there's ticket about it too.

**Comment by agrogers** [comment]
I think this is what you were referring to:
https://github.com/AndBible/and-bible/issues/573

Regarding the name, 'Bible Study' conveys to me something that you do. A
google search results in bible studies that you can attend or do.

'Study Bible' conveys the idea of a thing - a book or tool. A google search
returns bibles that are intended for study.

I think of And Bible as a study bible on steroids.

Prepending 'The' conveys to me that this is the best study bible - the one
and only study Bible that you need. At present i believe that - there is no
better mobile device app that allows for better study.

So I would propose the following changes:

<string name="app_name_short">Study Bible</string>
    <string name="app_name_medium">The Study Bible</string>
    <string name="app_name_long">The Study Bible app, by And Bible
Open Source Project</string>

?

I would drop the 'The' from the short name only if it doesn't fit on home
screen icon titles. It didn't fit on mine.

I would drop the 'And Bible' from the medium name. It seems a little
confusing.

I like the long name - makes clear both what it is and who is making it.

These are just my thoughts. Keen to hear other's thoughts.
___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
App name has been very long "And Bible" and many people still call it "And Bible" (myself included) so to avoid confusion, I think app_name_medium could have it still in parenthesis. 

These are the contexts in which it is used:

![image](https://user-images.githubusercontent.com/5811789/124427413-07b24300-dd74-11eb-8f77-09884a91270c.png)

![image](https://user-images.githubusercontent.com/5811789/124427428-0c76f700-dd74-11eb-9b4e-7d72033a2a85.png)


BTW need to remember playstore-description.yml also, there it is repeated in title.

**Comment by tuomas2** [comment]
I also am willing to hear others on this. Especially those that were involved in thinking about last app name change, like @timbze if I recall correctly.

**Comment by tuomas2** [comment]
Hmm, suggested ne long version "The Study Bible app, by And Bible Open Source Project" is too long for Play Store (hard limit is 50 chars). Ours would have 53 chars.

**Comment by agrogers** [comment]
Could we remove ' app'?

**Comment by agrogers** [comment]
I'm fine with just reversing 'Bible Study' and leaving the rest the same.
Adding 'The' is secondary.

**Comment by tuomas2** [comment]
Well, removing "app" or "the" would make it fit. Opinions?

**Comment by tuomas2** [comment]
"Bible Study" over "Study Bible" was chosen, I think, because "Study Bible" (to me) is highly associated with a specific commentary bible. If people (in different languages) expect to get a study bible, they will be disappointed, because all they get is often only bible doc in their language and all other material is english.

**Comment by tuomas2** [comment]
But in english "The Study Bible" probably works a bit better.

**Comment by timbze** [comment]
It seems the discussion in 3.3 was between Tuomas and me. Didn't have any other active devs at that point
![Screenshot from 2021-07-05 08-14-11](https://user-images.githubusercontent.com/35117769/124484832-23641c00-dd69-11eb-9b12-0f5342b5ffa8.png)

I think "Bible Study app" and "The Study Bible" are synonymous in one sense.

However, as Tuomas said [in a post above](https://github.com/AndBible/and-bible/issues/1235#issuecomment-874068227), "Study Bible" is often used as a term for a specific commentary, etc. (E.g. MacArthur Study Bible, ESV Study Bible)

"Bible Study app" indicates that it's a tool to study the Bible. "The Study Bible" could indicate the same, but it would also much easier be taken as "the best commentary/cross-reference/footnote package"

Also, I can see that just "Bible Study" by itself can be a bit vague, or sound incomplete.

But I think keeping "Bible" as the first word for the app launcher is the right thing to do. My phone shows "Bible St...". In such a case it might as well be "Bible Study App" also, since I don't see the last part in the launcher anyway. And when I go to Settings > App list then it would show "Bible Study App". It could even be "Bible Study App (And Bible)"

I also think that though we could perhaps do things to make it better for persecuted countries (we should not make it worse anyway), there are other ways outside of And Bible that can help in hiding the icon, etc. See #178 

I'd be ok with using "The Bible Study app", but then again it would become too long for play store.

I'm leaning toward leaving things exactly as they are.

**Comment by timbze** [comment]
> I'm leaning toward leaving things exactly as they are.

Or perhaps change `app_name_medium` to "Bible Study app (And Bible)"

**Comment by bvahedy** [comment]
I agree with Timmy on this one, the word App needs to be there.

**Comment by agrogers** [comment]
There is already an app called 'The Study Bible'. And it is John Macarthur's version I believe:
https://play.google.com/store/apps/details?id=com.gty.macarthurstudybible 
So that is another good reason to rule that name out.

> Bible Study app (And Bible)

Can we capitalise the letter 'a' in app if this is going to be a name?

And perhaps add 'by'? It seems weird to me to have a name with another name in brackets after it. I liked the way And Bible had been reference before. And Bible has become the project or the group producing the app. The app itself has another name which is a little more user friendly.

So my preference would be...
- Launcher: Bible Study App (but we know that only the fist word or two will be visible)
- Medium: Bible Study App (by And Bible)
- Long: Bible Study App (by the And Bible Open Source Project)

On a PPT presentation I would  split the long name...
- Top of slide / Main Title: **Bible Study App**
- Bottom of slide / Subtitle: By the And Bible Open Source Project

Adding 'App' resolves my complaint that 'Bible Study' is something you do not a tool that you use.
Adding 'The' was just a way to try to convey the awesomeness of And Bible. It's not necessary.

**Comment by uniqueid001** [comment]
Just some notes and thoughts:

 * The play store listing and the app's launcher can be different (both the text and the icon)
 * Of course, there should be an obvious resemblance so that the two are recognizable
 * Only a short name will fit the space allotted by the launcher/home app
 * Blue Letter Bible names their launcher simply "BLB", presumably due to limited space
 * YouVersion names their launcher simply "Bible";  I know many people who seem to be unaware of the "YouVersion" identity and seem to think that it is the only Bible app
 * I think prefixing the launcher text with "The " is unhelpful: it is not descriptive, consumes limited screen space, and would sort in an unexpected position of the alphabet;  though in the Play Store listing I think it wouldn't be as bad since there is more space
 * As you noticed, "Study Bible" is the name of the launcher for the MacArthur Study Bible app from Grace To You
 * The previous change from "AndBible" to "Bible Study" moved only one letter later in the alphabet; changing from "B" to "S", or "T", would cause a greater change for users who are accustomed to finding it earlier in the listings, and would move it away from any other launcher whose name begins with "Bible" (eg "BLB" from Blue Letter Bible, "Bible Study" from OliveTree, "Bible Hub", "Bible" from YouVersion, "BiblicalTraining")
 * I can easily edit the text (and icon) of my home screen shortcuts since I use ADWLauncher
 * Of course naming is one of the hardest problems : )
 * The original "AndBible" name came at an early time for Android's existence when many apps were named "And _something_" to associate them with Android

**Comment by tuomas2** [comment]
Final conclusion: adding only "app" to medium name?

**Comment by agrogers** [comment]
Adding 'App' - capitalised - to medium name. Could also add to short name
but no one would see I don't think.

So the name would be 'Bible Study App'.

That gets my vote.

**Comment by tuomas2** [comment]
Should I capitalize App also for long version?

**Comment by tuomas2** [comment]
last change 9b46d3e4503d3f444b1a388c36abd082a0578ebb

**Comment by agrogers** [comment]
I would treat 'App' as part of the proper name. So yep, I would capitalise.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Done

**Comment by agrogers** [comment]
Sorry to reopen this. I have grown to like the title 'And Bible' more and 'Bible Study App' less since I have been trying to write some tutorials and documentation. For example consider:

1. 'And Bible has over 1600 Bible translations'
2. 'The Bible Study App has over 1600 Bible translations'

The second is very generic - which bible study app am I talking about? Where as 'And Bible' is a proper name (almost) and not a description. I also find myself referring to AB or And Bible in emails or conversation much more easily than 'Bible Study App'. Consider:

1. 'And Bible is a great app'
2. 'Bible Study App is a great app'

The second example feels grammatically incorrect to me.  That's because you would normally have to start the second with 'The' so it should be 'The Bible Study App is a great app'. But the proper name no longer feels like a proper name.

But I also have issues with the way 'And Bible' is supposed to be written - with the space between the words. Consider:

1. "This app has 1600 Bible versions. And And Bible also has 50 commentaries."
2. "This app has 1600 Bible versions. And AndBible also has 50 commentaries."

That first just looks so weird. You never start a sentence with "And And". The second is fine. Or consider:

1. "And Bible is great!"

How is the word "And" being used here? Is it a title? Or is it a conjunction? Either way it looks messy to me.

I don't really have any good suggestions. Just wondering if others have any similar feelings. 

I am probably feeling like the official name should be "AndBible" not "And Bible" or "Bible Study App"
The launcher name could still be "Bible Study" I think - or just Bible or even AndBible.
Maybe the long name could be "AndBible - The Bible Study App"

**Comment by tuomas2** [comment]
I think we can use 'And Bible' in some contexts like in tutorial videos (it is in full app name still, due to And Bible Open Source Project suffix). 

Should we establish it as an alias even somehow better?

**Comment by tuomas2** [comment]
Done in #1857
