### ISSUE TITLE
Background clicking is now not working

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1273]
Due to #1187 background clicking is not working at all.
Earlier it was used to stop highlighting etc. 
Need to think about how to fix this...

Perhaps these rules would work:
- If 1-click modal is open, close it first (and don't open again until next click)
- if there's highlight to be removed, do it first, and only next tap open 1-click modal

**Comment by tuomas2** [comment]
Now it is also impossible to change active window by tapping, without opening a modal. 
Fix: only open modal if window is already active.

**Comment by agrogers** [comment]
I did think about that issue. Changing windows by scrolling not clicking
works well. This is the way to do it when the bible window is showing
Strongs links.

Losing the first click is an option too but I feel that might mess with the
'single click to open a bookmark'. Sometimes it will be a double click.

But I am never sure about these things until I try it for a bit!

**Comment by agrogers** [comment]
One thing I would suggest is that the dialog is closed on a single click if it is already open and the user clicks on an alternate verse. I liked that way of closing the previous dialog. 

I can see that the selected verse changes when I click on a different verse. So that is a nice option. And of course I can close the dialog with the X. 

Oh, by the way, good work!

**Comment by agrogers** [comment]
I like both those suggestions you made.

I would add that if a dialog is open and the user clicks on a bookmark then the dialog should change to reflect the new bookmark selection.
