### ISSUE TITLE
Dotted-underline mode: word click show modal or strongs/morph window?

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1289]
Was mentioned here, but not really discussed as far as I can find: https://github.com/AndBible/and-bible/issues/1188#issue-930065669
> 3. Clicking on a word that is dotted-underlined indicating a Strongs (and possibly a Morph) number

I think clicking a dotted-underline word should always open the dictionary/morph window, and not show the modal first...
Except when there's a bookmark too, then maybe "which action do you wish to take"?

Now when there's a bookmark, and strongs is in dotted-underline mode, opening the dictionary is impossible.

Maybe action should be configurable. Maybe my thinking is wrong.

Clicking the verse number still does open the single-click dialog though.

**Comment by bvahedy** [comment]
I agree with you on this one:

>>> I think clicking a dotted-underline word should always open the
dictionary/morph window, and not show the modal first...

**Comment by tuomas2** [comment]
I'm also leaning towards making it same priority as bookmark click. It should not give ambiguous menu unless there are more same-priority entries.

**Comment by agrogers** [comment]
If I understand correctly then I think I disagree. The reason is:

Scenario as I think is described here:
1. Click on a dotted underline Strongs word
2. Shows a special dialog asking (View Strongs or View Bookmark Dialog)
3. Make your response and go to where you want to go.
4. [If it goes straight to Strongs then we lose the single click functionality - i think we are back to long clicking.]

So, 
1. If you want to view Stongs - it takes two clicks
2. If you want to view the bookmark - takes two clicks also

But current scenario is:
1. Click on a dotted underline Strongs word
2. Shows the View Bookmark Dialog
3. Edit the bookmark or click the Strongs button

So, we lose a special dialog and
1. If you want to view Stongs - it takes two clicks 
2. If you want to view the bookmark - takes **one** click

So the new proposal if I understand it correctly always requires the user to take one more step to view the bookmark or add a bookmark.

Plus, we are not interrupting the flow of use with an extra dialog.

But, I agree that most times a user clicks on an strongs underlined word they probably want to go to strings definition.
That functionality is available still... by showing the strongs numbers.

**Comment by agrogers** [comment]
Hmm....

1. I think the intermediate dialog is still a bad idea - makes more clicking not less
2. But perhaps the ability to manipulate bookmarks with the underline words should be disabled and it does just go straight to strongs

**Comment by agrogers** [comment]
Perhaps we could turn the verse number into a link which opens the bookmark modal and the underlined words work like they used to...

**Comment by timbze** [comment]
IMO the dotted-underline mode should be for easy access to strongs definition. Anyone who uses the mode usually would also know about the long-press. So it should not take 2 clicks to get to strongs definition in that mode IMO. Unless there's also a bookmark than it would be ambiguous selection

**Comment by tuomas2** [comment]
Strongs are not enabled by default anyway. I think strongs is kind of "advanced" feature, isn't it?

**Comment by tuomas2** [comment]
though they are very easy to access via toolbar button...

**Comment by timbze** [comment]
Yes it is advanced feature and I think even if a new user tried it out they would get the feel that it's about the words and then they can easily disable the mode again for other usage

**Comment by agrogers** [comment]
Sounds good to me. Are we still considering a special dialog when the user clicks on a word that also has a bookmark? I am not convinced yet that that is superior to just showing the bookmark dialog with a Strongs button on it.

**Comment by tuomas2** [comment]
When there are 2 or more options for user to choose we use AmbiguousSelection (="special dialog")

**Comment by bvahedy** [comment]
This works beautifully now in 531.15 build, awesome work!

**Comment by agrogers** [comment]
Great. I like it too. Only change I might make is to move the Strongs
button to the top. If they have the Strongs links on then there is a good
chance that is the info they are interested in.
