### ISSUE TITLE
Enabling sync always syncs the wrong way

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1297]
Scenario
- I have a Bible window open at the verse I want
- I open a new window and change it to the Bible I want. It is not synced. And it is at some random verse. 
- I change it to sync. 
Sadly the top window with the verse I am reading changes to the random verse in the newly synced window. I want the new window to sync to the top existing window. 
- I then also can't seem to get back to my original verse using the back button
- so I select the first window and browse for the verse again.

Its possible I am not doing things right. But the way I think it should work is
- when making a window sync it should always sync to some other window. The new window should never be the master.

I believe it is reproducible.

**Comment by bvahedy** [comment]
Andrew,
I believe that's how it's suppose to work.
In a new workspace the first window always had the sync checked.
 Since your first window has sync enabled, then tapping on the plus icon to
open a new window will create a window with the sync checked.

Also if you have multiple windows open, in order to create a new window to
sync with a current window, you need to tap and hold on the first window
icon that has sync checked. The new window then will be synced with the
first window.

**Comment by tuomas2** [comment]
I also feel that it's often "wrong way", though I have thought that there might be need for both ways separately (i.e. sync this window to others, and sync other windows to this).

**Comment by agrogers** [comment]
Wow, there is more options there than I new about. I think i will need to
play with it try and understand what you were describing.

Thanks for the info.
Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Related to #940

**Comment by tuomas2** [comment]
And somewhat related also #648
