### ISSUE TITLE
Make copy function to bible that copies only plain word/words of the selection

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1371]
Probably adding new option in share/copy dialog.

**Comment by agrogers** [comment]
I like it.

**Comment by tuomas2** [comment]
> Currently when copying a word it adds ... and Bible ref. to it. It just needs an option to just copy the word or selection without any additional characters attached to it.

**Comment by bvahedy** [comment]
We could put it under, "show full verse" option, so when it's off it only contains the selection without any ref or extra chars. This way we could avoid adding new strings which would push this mod back to 4.1 implementation which could coincides with Jesus' return😁.

**Comment by timbze** [comment]
I'm starting to think it may be good to change context menu to simply have "Copy" and "Share Verse".

"Copy" would just simply copy the selected text, though maybe should still do a custom copy so that footnote numbers would not get copied.

"Share Verse" would do exactly what current "Share / Copy" does. The dialog would still have "Copy" feature like now.

**Comment by agrogers** [comment]
Closed by https://github.com/AndBible/and-bible/pull/1968
