### ISSUE TITLE
Text area jumps when moving cursor

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1439]
In study pad, when editing study pad text entry, I have issue with long text entry. When I tap on the bottom of the text to move the cursor (in edit mode), text area jumps so that it's top is shown (bottom can be then either invisible or covered by the keyboard).

**Comment by agrogers** [comment]
It does. Solution for me is to take shorter notes :)
But this would also be a good option:
https://github.com/AndBible/and-bible/issues/1339

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It should not behave like this. Do you have idea why is it behaving like that in the first place? I'm afraid #1339 might not solve this at all (it could still behave same way).

**Comment by tuomas2** [comment]
and I don't think I would like to use #1339 for study pads anyway.

**Comment by tuomas2** [comment]
Related: 
- #1001

**Comment by agrogers** [comment]
#1339 (second point) is to have a 'normal' text edit window. The JS one is
perfect (on a phone) for shorter notes. But when i have been doing my
devotions i tend to write more tied to a single verse. I am also not
jumping around from passage to passage. I will just be on the notes for one
verse for an extended period. It is at those times that i have wanted a
fullscreen, standard edit window. I can't recall exactly why the current
one in maximised mode bothered me - i think it was all the wasted space in
padding and margins around the text. That could be addressed in a JS form
as well. But I cant recheck it now because the last beta doesn't hides my
notes window under my keyboard. No devotions tonight ;-)

As for why it jumps, i have no idea really. It just seemed like a click
event triggered a focus event which gave focus to the edit control which
brought the top of that control into the window.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
You can use any 537.x builds (downgrading is possible because same versioncode).

**Comment by agrogers** [comment]
Thanks Tuomas. I was just being lazy :)
You have been releasing so many updates I thought i would wait for a
little while longer to see what you came up with.

Also, i haven't had the crash when I return to the app. You thought you
found the silly bug for that one - I think you have too. Well done!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I don't think I have time to anything anymore today :-P

**Comment by tuomas2** [comment]
(already working day was delayed until 12:00 because of these...)

**Comment by agrogers** [comment]
I was surprised so much had happened - I thought Thursday was normally your day

**Comment by tuomas2** [comment]
checked quickly and noticed that this actually affects even couple of days old builds, so this is not introduced by recent changes. I guess we just didn't notice this until #1433.

**Comment by agrogers** [comment]
Correct, it's been doing it for weeks. I noticed it about the time I raised
the other issue - at church 2.5 weeks ago I think.

**Comment by tuomas2** [comment]
I believe it has been doing it since studypads were introduced, unless Android Webview has changed somehow its behavior.

**Comment by tuomas2** [comment]
But surprise surprise: it does not happen on my mobile... :-/
