### ISSUE TITLE
Open Bible verse link in new version

### ISSUE THREAD

**Issue by BryceSteuer** [AndBible/and-bible#1519]
A feature that I would appreciate in AndBible is the ability to open a verse link in a different version. Currently (for instance on NASB) you can click a crossreference link and it will open in a mini-window of the same version. Or you can long-press the link and you will have two options, "Open link here" and "Open link in new window". The option I would like to see is "Open verse in different version". Perhaps this might seem low priority at best or minute at worst, but I personally would find it useful.

**Comment by tuomas2** [comment]
If the link does not specify the version (some might, but usually not), just change the version in links window and further links will open in that version.

**Comment by timbze** [comment]
It seems NASB and ESV both specify the version: https://github.com/AndBible/and-bible/issues/1198#issuecomment-890911841

I agree this would be a great feature, or allow to choose a default version that it should always open as.

**Comment by BryceSteuer** [comment]
My thought is to create ability to hold down link and choose the version to open the verse link in without opening an intermediate window (maybe with a "don't ask again" for users who are not so inclined). Although there are probably other areas of the app where this can be reasonably implemented.

**Comment by tuomas2** [comment]
other options:
- make option to ignore links translations when long-clicking them (?)
- Make option in links window to lock translation

**Comment by tuomas2** [comment]
@BryceSteuer are you interested in implementing yourself? If so, wait for some time for concensus on this ticket and then you can implement. I would like to hear @agrogers  opinion first at least before deciding.

**Comment by agrogers** [comment]
A few thoughts :
- I rarely ever use that long press option so I don't have any strong feelings about it 
- I have wished for a default translation option. Just finding the NASB in my growing drop down list has got a little tedious. Putting that translation at the top of the list is something I would make use of 
- I have never really wanted to choose a translation when opening a link. However there have been many times when the translation that has opened has been unexpected and I have to change it. It definitely doesn't use the last selected translation for me. 
- I think the target window should never have its translation changed without user approval. So I definitely support ignoring the version provided in links. 
- I probably wouldn't add another option to lock the translation. And it wouldn't be needed if the user had to interact to change the translation.
- I don't have any opposition to adding extra options to the long press menu. I see this menu is for advanced users and it is unlikely to bother the new user.
- perhaps that menu could show the last three translations used as options to choose from. But which type of window do they open in - new or current? If we want to provide both then our menu options have increased by 6. That seems a little excessive. A special dialog rather than a popup menu would now be preferred. 
- Maybe there is a case for a preferred document(s) in each type? That would help determine which commentaries or dictionaries to look up for quick access features we are considering.
- I have never found it that bothersome to open a link, then choose the translation from the button list. But this is a three click process - select the window, push the translation button, choose the translation from a potentially long list.
- perhaps four options only are needed: the current two and two that append ' and set translation'. If they are selected the target window is automatically selected and the action bar drop down is automatically shown. If the preferred translations were also listed at the top then they would be easier to find.

**Comment by tuomas2** [comment]
> I think the target window should never have its translation changed without user approval. So I definitely support ignoring the version provided in links.

This could be done separately anyway, for bible documents. If link goes to commentary / dictionary, then translation should be obeyed. (created #1521)

**Comment by timbze** [comment]
In my opinion, this is properly fixed by #1521 (9ca77ff). Now if you select a certain version in the "special" window, all Bible links open in that version. I had this issue before too because depending on which module I would open a verse from it would always open in different versions. It's consistent and good for me now.
