### ISSUE TITLE
Enable bookmarking in an 'all references' window

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1546]
I wanted to add a bookmark to a verse i read in the 'Show all references' window. But alas, bookmarking does not seem possible there. I thought there was already a ticket in the system for this but I couldn't find it.

![image](https://user-images.githubusercontent.com/13920678/128656217-301479a8-3095-4857-93e8-1a7c0edd3706.png)

**Comment by tuomas2** [comment]
We could implement creating a bookmark from there BUT it would not be displayed in that view, which would be confusing to users, so we should AT LEAST show toast message to explain it to users. So, if we want to do this, it will be 4.1+

**Comment by agrogers** [comment]
Would it be possible to show the little icons perhaps?

Even if it is not shown the user would still see them in the verse action
dialog after clicking on it. That would be enough for me.

**Comment by tuomas2** [comment]
No, nothing will be shown. 1-click modal also would not anything in multi-doc (compare / "all references" view). The complication is not about displaying, but more about syncing bookmark data between windows. It would be complicated to implement synchronising bookmarks to those views in a robust way. 

Or maybe I can re-think this still, but that's why I did not implement it in the first place.

**Comment by tuomas2** [comment]
So summarising, unless I figure out something clever for that syncing, it might be better not to implement it at all (?)

**Comment by agrogers** [comment]
Yeah, i agree. It's important that we can see all the bookmarks already on
the verse otherwise we end up creating the same bookmark multiple times. So
yes, I think leaving it is a good idea :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Wont fix
