### ISSUE TITLE
Ensure the action bar is hidden when editing notes

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1549]
I think the hiding of the actionbar when editing a note is a (great!) new addition. I like it. It gives even more space. However the bar doesn't always disappear it seems.

On the screen below I edited the note from the ... button but the action bar remained. I think this is a bug.

![image](https://user-images.githubusercontent.com/13920678/128656520-04782c46-d6a2-4da4-86f3-b3a975084f38.png)

**Comment by bvahedy** [comment]
I'm unable to duplicate this. The menu bar hides Everytime.

**Comment by tuomas2** [comment]
It is not removed ever, and should not be removed. 

The functionality is as follows:
- If there are 2 or more windows, use "panning" to scroll view so that text is visible and keyboard does not overlap with editable text. (then menu bar is invisible often)
- If there is 1 window only visible, just resize the window such that keyboard gets the space it needs.
