### ISSUE TITLE
Logo with Non-religious Symbols

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1609]
Hello, 

Just checking to see if there has been any progress on a ambiguous or non-religious symbol for the logo? 

Ben, you will appreciate this, I just read an article in The Christian Post, that if true shows the need for such a logo. 
I hope it is OK to link here, if not please delete this post. 

https://www.christianpost.com/news/taliban-hunting-for-christians-inspecting-phones-for-bible-apps.html

Debra

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tuomas2** [comment]
as a quick solution, I guess we could release side-release apk on github with completely symbols removed

**Comment by bvahedy** [comment]
Yes it is true, this has been going on for a long time in predominately
Muslim ruled nations.

**Comment by agrogers** [comment]
Could a widget be provided that has a different icon and which simply opens
the app. Then the current icon shortcut could be hidden or removed.

**Comment by tuomas2** [comment]
I guess to make it completely safe, we should allow user to choose an icon (because even non-religious icon and name might become known by persecutors) and have some kind of "cover app" (pretending to be something else than bible app) that will launch and a password-protected entry to real bible app. 

Related: #178

**Comment by tuomas2** [comment]
Now that I'm thinking about it, it might indeed be needed to make a persecuted-country friendly variant of And Bible officially available separately. I'm not sure if app name, icons and everything can be changed from code level. Those things are defined in manifest etc... That version could be released through play store (not sure if it is needed actually) and advertised somehow from main app and homepage etc.

**Comment by tuomas2** [comment]
Advanced launcher app (like Nova launcher) can make already icon change and app name change in launcher level, but a bit more technically knowledgeable persecutor will quickly find the 'real' app name list via system settings...

**Comment by timbze** [comment]
I think it's possible to have a separate manifest for a separate "flavor" with those values overridden that you want.

**Comment by tuomas2** [comment]
Maybe the challenge is to make just the right people know that there is such a variant available.

**Comment by agrogers** [comment]
Here is a github repository that shows how to change the app icon and name
programmatically

https://github.com/myinnos/AppIconNameChanger


I imagine it is not too hard for someone who knows what they are doing to
change the internal icons - Bible to something else, normal icon to
something else etc.


There are already apps that allow you to password protect other apps. I
think most launchers have that Mi UI has it I believe. So password
protecting not really our responsibility

**Comment by tuomas2** [comment]
It looks simpler than I thought. Thanks!

**Comment by cmahte** [comment]
I replied (or started to on an earlier thread/this thread) about using a
letter instead of a logo.

Android allows for sub items like contact names to appear on the desktop
and shows the first letter as the icon.

That seems like at least a possible way to lessen the obviousness...  allow
the user to choose any module as the main screen icon, so that the work
opens directly. and it looks just like a contact item ...

It still has the problem of showing up in the apps menu.... I'm all for
having a clone version that is described as a "book reader" and allows for
epubs to come from some not-so-obvious source (like project gutenberg?),
but also has alternate sources that include sword modules.

but, since I'm an observer here and not really active participant... (sits
back down.)

**Comment by cmahte** [comment]
taking it one step further.

a "book reader" on the play store that doesn't have the alternate sources
preconfigured, but possibly available from some setting or toggle...  and a
visually similar "book reader" apk that could be sideloaded that does have
the alternate sources preconfigured.

Such a method ... where the app is clearly multi purpose... and a speaking
ebook reader would be useful, seems the best way to proceed.

**Comment by tuomas2** [comment]
ebook reader is far in the future (if ever will implemented), not easy to do. But something else we can do, I believe, before 4.1.

**Comment by timbze** [comment]
> Here is a github repository that shows how to change the app icon and name programmatically

I think user-configurable-icon and name is much better from security standpoint then just another variation of the app. (Since that seems to be possible). That way there can be 1000s of variations because each user can pick what works best for him/her.

**Comment by bvahedy** [comment]
I wish there was a way in the Andbible app preferences we could have a
setting that when checked it would switch all icons to non religious and
allow the user to select a  logo and a name of their choosing then ask the
user to reinstall the app to make all changes take effect. Because those
looking to persecute Christians and Jews will know what to look for, that's
why it has to be the user's choice of logo and name.

**Comment by bvahedy** [comment]
I guess Timmy and I are on the same page, we were typing at the same time.

**Comment by Dleemuse** [comment]
Thanks all for the input. I love Ben's idea. I was just thinking having a non-religious logo would not be enough, as all a person searching for Bible apps would have to do is open the app to know it was a Bible. I was going to ask if there was a way to make it look like something other than a Bible once the app itself was actually opened. Is this possible?

I have a friend who is Nigerian (lives in Nigeria), & is an evangelist. He currently has AndBible on his phone. I emailed him to ask if he thought a logo with Non-religious symbols would be useful, if he would use it, & if he thought others would use it. Here is his reply...

"I agree with you that the AB TEAM should create a logo that is not easily identify with a fake page. We are not good at design so we may not be able to suggest a type of logo.

The situation in Afghanistan is giving all of us concern here because Nigeria is second to Afghanistan in terrorists rating. It will embolden the terrorists and their sponsors here.

Moreover, we have a government that is sympathy with terrorists & killer- herds men. We need prayers."

This man is a faithful preacher of God's Word, his life & the lives of others are in constant danger in Nigeria simply because they are Christian. He personally has asked me to pray for him as at any time they can be detained, robbed, kidnapped, or killed because of their faith. I tell you all of this to make it personal. If there is any possible way to allow people to use a different logo, that would be great. And it would be even better if somehow as Ben mentions, to not just have a different logo, but once the app is opened for it to not look like a Bible (that is why my friend was asking about a fake page). 

If you guys can get this done, please let me know, so I can pass the information on to him. 

Thank you, I appreciate all the work & time you all put in on AB! 

Debra

**Comment by bvahedy** [comment]
Well, one way to solve that is when in the app settings you turn on
"persecuted country" then when you open the app it would show a fake
weather page and the user needs to swipe left 5 times in order to enter
Andbible. The number of swipes should also be comfortable in the app
settings and weather is right or left or up or down swipe configuration.

**Comment by Dleemuse** [comment]
That sounds like a great idea Ben! Is it possible to do something like that?

**Comment by agrogers** [comment]
Interesting idea about a fake page. Perhaps simpler would be a notepad.
There is already an editor in AB. Or calculator.

**Comment by bvahedy** [comment]
We could give them two or three screens to display as a fake page or let
them pic a picture from their gallery. The problem with presenting a
calculator is that 1) if it's just a picture of a calculator keyboard then
when they type on the numbers and find that it's not working they will get
suspicious. 2) if it is a working calculator and assuming Toumas can fire
the calculator app from within Andbible then the Taliban may try to do
their banking on it. May be I'm assuming too much here, but we're never
know the extend of their cruelty.

**Comment by tuomas2** [comment]
BTW We don't have dari nor arabic translation in And Bible UI, so we might have *some* users there but not many, as those people don't speak english very much as far as I know.

**Comment by bvahedy** [comment]
We may not have UI translation, but there are Persian and Arabic Bible that
they use to read the Bible.

**Comment by Dleemuse** [comment]
In Nigeria, and other parts of Africa, where most of our Christ Evangelical Foundation (the international correspondence Bible College I work for) students live, they all speak English to one another as there are so many tribal languages that they themselves do not understand, & as I mentioned, there is a lot of Muslim persecution. I don't know how many people would use the alternate persecution app or settings, as most of our students are poor & some do not have a smart phone that can load AB. Just recently I told a student in Zimbabwe about AB, he tried to load it but couldn't get it loaded, so, that same day he went to shop for a new phone just so he could download AB. He didn't have enough money, but he is trying to save enough to purchase a phone so he can get AB. I think these & other stories are a testament to how powerful a tool AB is. In any case even if not many people can use/download AB because of certain circumstances, there will be some that can. And if it is a small number that can, I know they would still appreciate having the option for a different logo & fake page. And, I am spreading the word about AB more & more in Africa, so who knows in the future how many users "we" (saying this like I am part of the AB team, lol) will have that would use & appreciate such an option. I mentioned a while back how excited my Nigerian friend was to learn there was even such an thing as AB. He was like a kid in a candy store finding out how easy it is to study the Bible with AB, (He even mentioned jokingly that we should name the app "Bible Study Made Easy). But it was more than that, I could hear & see the spiritual hunger & thirst he had to use AB to be able to have a tool that would not only help him grow personally, but his family, his church, & all those he enangelizes on his evangelistic trips not only in Nigeria, but other states across Africa. 

If you would kindly keep something in mind for this feature, I believe many of the people I have contact with in Africa would need a very user friendly option in order to implement the persecuted country settings to make their AB not look like a Bible.

Thank you ("wink, wink" - your newest AB team member, lol) 

Debra

**Comment by agrogers** [comment]
That's a great testimony Debra. Thanks for sharing. I think I speak for
everyone on the actual team ;-) that we want to make AB as helpful to
everyone but especially to those who are suffering for Christ. I will use
my limited skills to try and progress this along.

**Comment by tuomas2** [comment]
I'm also committed to prioritize this towards 4.1 release.

**Comment by agrogers** [comment]
Been some good ideas raised above. My summarised thoughts:
0. Single version that installs as using standard icons and name.
1. Include a 'Persecuted/Covert' option that
2. Changes the icon to a calculator
3. Icon opens AB as a real calculator that does real calculations. This is
the first AB screen.
4. User types in a special number/pin code to 'unlock' and open AB.
5. Covert option also changes any religious icons to alternatives
6. Maybe desirable to automatically close the app when changing to other
apps. That is, if the app was open and someone looks at the open apps they
would see AB.

Here is an open source calculator
https://github.com/SimpleMobileTools/Simple-Calculator

Or creating our own could be easier.

This would possibly be one of the very few Persecuted Bibles available for
a mobile device. That is definitely something that appeals.

Regarding point 5, this almost seems unnecessary to me because if someone
can see the icons within the app they can probably also read the text
within the app. So changing the icons is the least of our problems. But I
couldn't imagine that implementing this feature is too hard so it could be
included.

**Comment by timbze** [comment]
- Might have to disable widgets for "persecution" version
- Also maybe change app identifier, which is currently something like "net.bible.activity"

**Comment by tuomas2** [comment]
also, maybe bible modules should be installed to internal data only

**Comment by agrogers** [comment]
If the identifier is to be changed then should that happen for version 4?
Many changes for this release that installing along side v3 may be helpful.

**Comment by tuomas2** [comment]
Identifier is something we can not change (it would mean adding a new app to Play store etc), but if we release another "persecution-friendly" version, then we can change it there.

**Comment by cmahte** [comment]
There are multiple vectors how this persecution happens:

1. When you travel, border "guards" demand you unlock your phone so they
can inspect it.  They have 1-3 minutes to review what is in your phone
visually.  Usually they want to find something to be able to charge you a
minor "fine." But in certain places, the presence of Christian literature
would also get reported and could turn into type 3 immediately or later.

2. Governments in some countries monitor and censor internet traffic. In
these cases transmitting sequences like "bible" may introduce type 3.

3. Officials (or the militia) appear with your name and exactly what they
want (here in the USA they have a warrant, but elsewhere... maybe they just
show up.) Usually this is because you are a high profile person that has an
opposing view to the official with the warrant or who he works for, but the
'what they want' doesn't have to be anything related to the differing
opinion.

What have been discussed will help limit type 1 intrusions. But those are
the type that cost you 10 bucks to continue travelling. Addressing these
will help limit type 3 that result from type 1 discovery, but the life
threatening issues are usually type 3.

I've listened to people describe the guard interaction, and I've even
walked through a few those borders myself. The guard won't read English
well, but likely would recognize "Bible" as contraband. But those first
level inspectors aren't really trained what a Bible is, only that it's
against the prevailing world view. The local and english spelling of
"Bible", and a + shaped cross are likely all they would recognize. The fish
in the current Icon... it wouldn't stand type 3 scrutiny for 1 second, but
it's not really much of a threat at level 1 unless it's widely used in that
place. The name of the app is more of a threat than the image above it.

My recommendation: The alternate app that has an obvious legitimate purpose
(like a book reader) and is actually in use by people for that legitimate
purpose, like a book reader. When you enable alternate sources, it also
becomes a more powerful study program. That will help address #3, even if
they find it, it can withstand the keystrokes and doesn't look out of
place. If you enable the Biblical source locally by loading from SD card or
bluetooth transfers... that helps with number 2. It's not obvious at the
icon level or the menu level or even if someone leaves scripture in view,
unless the inspector has specific knowledge about what scripture looks
like, which could be dangerous for the inspector.

To avoid type 2 discovery, Bible shouldn't be in the name, or the icon, or
in the network traffic. And there are likely 100 other key words to avoid.
but "Book" isn't one of them.

To avoid type 3, again... a second calculator app on a phone is going to
look fishy, especially when the name of the app on the apps list contains
'bible'. And the other 2 people you visite that day also have that same
exact app. It needs to be something that passes someone who does know what
christianity looks like, and knows enough about Android OS to notice things
out of place.

**Comment by Dleemuse** [comment]
Lol, thank you Andrew, I appreciate the real AB team. Thanks to everyone working on this feature!

Debra

**Comment by tuomas2** [comment]
@cmahte good points. Need to think about this. As I said, implementing a full epub reader in And Bible is not a solution for 4.1. It's simply too much work. But you may be right that *just* a calculator might not be good enough, because that kind of things a professional persecuter can easily learn to find.

**Comment by agrogers** [comment]
A few comments:

1. I have had multiple calculators installed on my phone at times - usually the default and then a fancy one. So i wouldn't have thought two calculators (obviously with different icons) would be suspect. And every phone has a calculator - so I think it is a very innocent choice.
2. It would be possible to include many different calculator icons for the user to choose from - that would make it much harder to identify (below are just a few of the ones i can provide) 
3. Providing options to the user to choose a color theme of the calc is probably not too hard either.
4. A calculator could be very lightweight so would not add too much to the size of AB
5. A book reader is possibly harder to implement and larger in size and requires books for it to look legit. A calculator requires no extra setup. And a book reader would be one app that a persecutor might give more attention to. That would be where i would start if i were looking for a bible or suspect material.
6. And a calculator is perfect for entering a code to unlock it.
7. And yes, the app could not be called 'Bible' - just 'Simple Calc' or any number of predefined options the user can chose from. Or if it is easy enough they could make their own.

![image](https://user-images.githubusercontent.com/13920678/130405478-d4e64418-52a8-4cc7-b62b-9584acf6ca2a.png)

**Comment by bvahedy** [comment]
I like it, especially the fact that you can unlock using a code on the
calculator keyboard which they can setup in the app settings.

**Comment by cmahte** [comment]
For someone in a professional field that can explain it, yes there's
nothing weird about a 2nd calc app. But from a head hunters standpoint, it
would be noticable especially if they keep seeing the same app.  And
especially if it's in a remote area. Learning English or at least the
business language is global, and even in the most remote places, a book
reader that speaks aloud won't draw much suspicion.

As I mentioned the normal mode isn't initially religious persecution but
simple graft. They make their living on fines. They start with pics and
emails and move to financial apps.... Something that they can argue with
you about and demand a fine, and some idea what level of fine is going to
be successful. Stuff that looks like it might have a bank statement....
That's higher that book readers

>

**Comment by Dleemuse** [comment]
I like the calculator idea where people can put in a code, & it seems an innocent looking option, because everyone has one on their phone. Just a thought though, do you think people would normally download a second calculator? I haven't ever done that. Having said that, I don't know that having a 2nd calculator downloaded would draw suspicion. But I do imagine that searches by persecutors can be through & smart.

**Comment by tuomas2** [comment]
It could be something a bit "specialized", like time calculator, currency calculator or something similar. And there could be other ideas too that we will have that will make it a little different than very basic calculator. Let's see.

**Comment by uniqueid001** [comment]
* It is feasible to create a variant (build type + flavors) with different appearance and functionality.  It can have a different logo, launcher entry, title, and application id.  I have some experience with creating variants, so I could begin preparing that.  Naturally the majority of the work is determining the alternative functionality to provide and implementing it.

 * As noted, the existing application id must be maintained for continuity of updates for existing users, and to preserve the history and number of downloads and ratings.  It would simply be separate from the new variant.

 * Good point about the recent tasks revealing a Bible text in the preview.  The variant can apply the [android:excludeFromRecents](https://developer.android.com/guide/topics/manifest/activity-element#exclude) attribute to address this.  I, for one, would not want this set for me but that is because I do not need to hide my apps.

 * If there is a real value in changing the app's appearance (dynamically), not just the launcher and app info, then I think that can be achieved using themes.  I do not have experience with those, however.

 * Analyzing the potential threats, as cmahte did, is key to ensuring that the results actually achieve the goals.  One of the biggest limitations of providing a single app is that once it is known and recognized then it is no longer a discreet secret.  The more technically capable the threat, the less effective these measures will be.  Once the app's identity becomes known it is no longer effective at hiding.  I think the ideas here do have value against the less coordinated and trained attackers who may simply perform a visual scan for anything that looks recognizable.

**Comment by bvahedy** [comment]
Your point is valid that the persecutors could also download the app and see what it does. That's why I suggested a user configurable image, they could pick an image from their gallery and configure a gesture to open the app. In addition to not showing it in the recent apps screen.

**Comment by tuomas2** [comment]
I'm thinking if it is wise/necessary to put it at all to Play Store etc. or should we keep it only in F-droid and Github as a downloadable apk? We can put some advertisement / notice about its existence to standard AB help dialog etc so that people can download it if they need it.

**Comment by agrogers** [comment]
It's a good option too. My concern would be that people may not find it.

I would still go with one app with a fancy welcome screen that asks them if
they want Covert/Persecuted mode. At least all of our users will know about
it and can share that info. And the thousands who need it will find it.

If there is a bible app available that does a better job than what we have
outlined above then I (and anyone here?) have never heard of it. That would
mean that whatever Persecuted Christians are presently using is much more
inferior than what we have outlined.

I feel like we are trying to make something that helps 99% of Persecuted
Christians but will be so secure that only 50% of them will ever discover
it. Whereas we could provide something that is way better than anything
else out there and which suits 90% of Persecuted Christians all of who have
a chance at finding it. (all numbers purely made up ;-)

If some persecutors are as determined as described above then we need a
very covert way of distributing the app as well as a very covert app. They
could just do a file search for KJV and find what they are looking for. I
just can't see how we can make it as safe as what we would like. For the
truly determined there will need to be something much smarter than a
different icon and id. So I would aim to help the 90% with a pretty secure
and say an extra prayer for the other 10% who need super secure app.

**Comment by tuomas2** [comment]
> If some persecutors are as determined as described above then we need a very covert way of distributing the app as well as a very covert app. They could just do a file search for KJV and find what they are looking for.

Not if we are storing everything in hidden data folder (which system prevents anyone to do any file search, unless phone is rooted).

I'm agreeing with your rationale. I'm excited that we might be able to serve the persecuted in a substantial way with these rather simple changes.

**Comment by agrogers** [comment]
I believe this is completed now. Well done.

**Comment by Dleemuse** [comment]
Thank you for this news Andrew! I have downloaded it & been playing around with it, I am hoping the working calculator will help fool some people. 

Thank you Tuomas & everyone for working on & implementing this new feature. I have already sent a message with the link for the update to my friend in Nigeria who I mentioned in previous comments.

Debra

**Comment by agrogers** [comment]
Thanks Debra. The icon will change to something more colorful and there may
be bugs to work through or other places that the official icon keeps
appearing that need to be resolved.

**Comment by tuomas2** [comment]
yep this is still in very alpha stage testing, hoping that it is not used in persecuted environment yet until ready to be released.

**Comment by Dleemuse** [comment]
Ok, noted, thanks Tuomas
Debra

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 11, 2022 at 10:08 AM, Tuomas ***@***.***> wrote:   


yep this is still in very alpha stage testing, hoping that it is not used in persecuted environment yet until ready to be released.
