### ISSUE TITLE
Make release notes for 4.0

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1648]

**Comment by tuomas2** [comment]
Related: #1647

**Comment by agrogers** [comment]
OK, those with permissions can directly update this document:
https://github.com/AndBible/and-bible/wiki/v4.0-Release-Notes 

Those who don't have permissions can add their suggestions to this ticket and I will transfer them across.

If we can collate a list fairly quickly I will try and make a video that goes over as many as possible.

**Comment by agrogers** [comment]
Hmm, not sure how friendly it is to multiple people editing it at the same time. Might need to be a little careful.

**Comment by tuomas2** [comment]
Google docs is friendly :-)

**Comment by agrogers** [comment]
Yes, very friendly. I have added all mine to the wiki now. If someone creates a Google doc let me know.

**Comment by timbze** [comment]
I think 3.3 vs 4.0 is what release notes should be. Some of it is, but I also see some lines that look more like "early beta" vs "release" (especially in the "improved features" section). For reference, release notes for 3.3 are [here](https://github.com/AndBible/and-bible/releases/tag/v3.3) (maybe there's more somewhere?).

Also, I think some of the lines could be joined together. To do that, maybe it would work to use a format something like: "New logo (#1568)". That way more issue numbers could be added to the same line.

Because my idea would be a major change to the current format, I'll redo the list here and I'll let @agrogers  and @tuomas2  decide on how to do it. I have not mentioned all items, because I think very minor issues don't need to be on release notes.

## New Features
- New logo, new menu icons ([#1227](https://github.com/AndBible/and-bible/issues/1227),[ #1568](https://github.com/AndBible/and-bible/issues/1568), [#1293](https://github.com/AndBible/and-bible/issues/1293), [#1329](https://github.com/AndBible/and-bible/issues/1329), [#1335](https://github.com/AndBible/and-bible/issues/1335), [#1400](https://github.com/AndBible/and-bible/issues/1400), [#1453](https://github.com/AndBible/and-bible/issues/1453), [#1454](https://github.com/AndBible/and-bible/issues/1454))
- Added a splash screen ([#1481](https://github.com/AndBible/and-bible/issues/1481))
- Single-click verse actions ([#1162](https://github.com/AndBible/and-bible/issues/1162), [#1169](https://github.com/AndBible/and-bible/issues/1169))
- Study pads ([#815](https://github.com/AndBible/and-bible/issues/815))
- Bookmark and highlighting improvements
  - Add word/character level bookmarks ([#590](https://github.com/AndBible/and-bible/issues/590))
  - Multiple underline highlighting ([#1407](https://github.com/AndBible/and-bible/issues/1407), [#1542](https://github.com/AndBible/and-bible/pull/1542), [#1556](https://github.com/AndBible/and-bible/pull/1556))
- New modals
  - Verse summary ([#1015](https://github.com/AndBible/and-bible/issues/1015), [#1416](https://github.com/AndBible/and-bible/issues/1416))
  - Bookmark/label information ([#1014](https://github.com/AndBible/and-bible/issues/1014))
  - Verse notes ([#188](https://github.com/AndBible/and-bible/issues/188))
- Active verse is highlighted
- Active window indicator ([#598](https://github.com/AndBible/and-bible/issues/598))
- Label list improvements
  - The label list is grouped to make it easier to find a label ([#1024](https://github.com/AndBible/and-bible/issues/1024))
  - Added the ability to set the Main label, Favourite label and auto assign label ([#1035](https://github.com/AndBible/and-bible/issues/1035))
  - Quick label assignment dialog for bookmarks ([#1104](https://github.com/AndBible/and-bible/issues/1104))
- Easier set up for new users, and added 'Easy Install' option to remove the manual downloading steps ([#798](https://github.com/AndBible/and-bible/issues/798), [#911](https://github.com/AndBible/and-bible/pull/911), [#1231](https://github.com/AndBible/and-bible/issues/1231), [#1163](https://github.com/AndBible/and-bible/issues/1163))

## Improved Features
- Options to customise the action of the Bible and Commentary button action (cycle through, popup menu, document selector) ([#597](https://github.com/AndBible/and-bible/issues/597))
- Option to disable reference overlay in fullscreen ([#920](https://github.com/AndBible/and-bible/pull/920))
- History listing improvements ([#716](https://github.com/AndBible/and-bible/pull/716), [#1645](https://github.com/AndBible/and-bible/pull/1645))
- Book chooser improvements ([#994](https://github.com/AndBible/and-bible/pull/994))
  - Make buttons more modern and add better highlight on currently selected book ([#988](https://github.com/AndBible/and-bible/pull/988))
  - Add option to order books/chapters from left to right (horizontal) ([#142](https://github.com/AndBible/and-bible/issues/142), [#1122](https://github.com/AndBible/and-bible/issues/1122))
- Backup improvements/fixes ([#776](https://github.com/AndBible/and-bible/pull/776))

**Many more bug fixes, features, and improvements. This is by far the biggest update that we have ever shipped!**

**Comment by agrogers** [comment]
I like it. Do you want to move it across?

**Comment by timbze** [comment]
> I like it. Do you want to move it across?

Sure. Done now. Thanks for laying a lot of the ground work with finding the new features etc :)

**Comment by timbze** [comment]
Made a few more additions/changes. See diff [here](https://github.com/AndBible/and-bible/wiki/v4.0-Release-Notes/_compare/3360e2fd97c60b066773fcea08e2d5f85469d485...fcf19ac4f4808c9418074e4f8cf8e7a3bfa75289)

**Comment by tuomas2** [comment]
Changelog for Play Store etc. Can be still changed. What do you think?

```
4.0
See "What's new" video: https://youtu.be/f2cf6-7liMo
Release notes: https://github.com/AndBible/and-bible/wiki/v4.0-Release-Notes
Highlights:
- Char-accurate bookmarks
- Bookmarks & My Notes merged & improved
- My Notes commentary view
- Study Pads for creating sermon notes etc.
- Strongs dictionary by clicking words
```

**Comment by timbze** [comment]
I think that's excellent. Are the links clickable in Play Store? If not then I'm guessing such long links are pretty much useless, but probably doesn't hurt to have them still.

**Comment by agrogers** [comment]
Looks good to me

**Comment by tuomas2** [comment]
> I think that's excellent. Are the links clickable in Play Store?

Yes they are
