### ISSUE TITLE
New Window ignores global settings

### ISSUE THREAD

**Issue by dbell154** [AndBible/and-bible#1735]
This is the opposite of another issue discussed: (When creating a new window via the popup menu on an existing menu, the new window should be the same type as the selected one.)

When I create a new window it does always uses the settings of the existing window. There does not seem to be a way to create a new window using the global settings. 

Example:
After creating a window, I can edit the settings of just that window for font, size, line-spacing and the similar global settings are unchanged. If I then create a new window either from the window menu, or the new window icon at the bottom right, it ignores the global settings and creates a window using the existing window as a copy.
The only way I can create a new window with the global settings is if I already have one before I made the modifications to my passage window, or create a now workspace.

![orig (Small)](https://user-images.githubusercontent.com/3357697/134735794-2fe02de4-397e-4076-97e3-a7eb4688d1b0.png)

Why it is important:
I like to have the passage text larger and in a serif font with less line-spacing, and be able to read footnotes, other documents in the window below with smaller text. So I would like any new windows to follow the global settings in the three-dot menu. Maybe you can add the New Window option to the three-dot menu. 

Also, I do notice that changing format using the global settings will change the settings for all windows. I'm not sure if that is a good idea as a default.

**Comment by agrogers** [comment]
Hi Dana

I think I follow you. I feel creating a new window using an existing window button should copy the settings of the window used to create the new one.

But the Add window button in the bottom right corner should create a window using the workspace settings, not the active window settings. It doesn't do that at the moment for me.

Finally, the workspace settings are intended to affect all windows that still use that setting. Without that functionality you would have no way of specifying settings for new windows (which is the problem here!) or being able to change all windows at once.

**Comment by tuomas2** [comment]
@dbell154 It is rather easy to reset the settings of a new window (go to text options and push reset button on toolbar)

But I agree that behavior of "add window" button could be changed.

**Comment by tuomas2** [comment]
Created issue about that: https://github.com/AndBible/and-bible/issues/1922
