### ISSUE TITLE
Make FAQ entry "why app is getting bad"

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1886]
Some people don't like the app changes. Need to write some FAQ entry why I / we think it is still highly reasonable to do the development.

**Comment by agrogers** [comment]
Yeah, that is a good idea. I always smile when reading the reviews and
seeing a 1 star review saying the update is terrible and then seeing a 5
star review saying the update is awesome.

It feels like the issue comes down to devices (older devices are sluggish)
and users (some users find change difficult). We can't do much about the
former. But I think we can try to prepare users better for future updates.

I rarely used bookmarks previously and never used notes. Now I use them all
the time. But more features almost always make apps more complicated. So
those people who like simple and dont want new features will be annoyed. I
have wondered whether we should upload the previous version as a new app on
the playstore. Probably a bit late now.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
We should also include the links to the video tutorials in the FAQ because I see in many of the complaints that the users don't know how to get to a function.

**Comment by tuomas2** [comment]
Wrote something. Can be improved.

https://github.com/AndBible/and-bible/wiki/FAQ#this-app-used-to-be-great-but-now-it-is-total-garbage-why-are-you-doing-this

**Comment by agrogers** [comment]
I like the title 😂

**Comment by bvahedy** [comment]
I have a friend that is an editor these are his suggestions:

This app used to be great, but now it is total garbage! Why are you doing
this?

Everyone has their opinion about the app and how it is changing. Obviously
we, the developers, love the changes we make.  It appears that a majority
of users love them as well -- but some do not.  Some complaints we have
heard:

   - things are getting more complicated
   - something that a user could do earlier, they can no longer do.

We strive to keep the app easy to use.  However, this app is not for
everyone.  If a user wants to simply read the Bible on their mobile phone,
without sophisticated tools, there are vast number of apps available to do
that.

Our priorities:

   - To be as advanced of a Bible study tool as possible,
   - To not overwhelm our users

If these priorities are in conflict, the first overrides the second, but
not unreasonably so.

Sometimes, we have to change existing functionality (that users have gotten
used to), to enable new, more advanced features.  If that is the case, we
try to make the “new way of doing things” more powerful, while not
sacrificing usability.  It must be an improvement on earlier functionality.

If you have trouble in using the latest version of app, please first see
our tutorial videos
<https://www.youtube.com/playlist?list=PLD-W_Iw-N2Mn5N3KSmNsb2IuBbR1XVLke>.
They are there to help you get around the app.
