### ISSUE TITLE
The window buttons disappear when there is only one window 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1918]
Did this happen in previous versions? This seems wrong to me because there is no way to configure the window settings because there is no window or window bar buttons. When I add a window both buttons reappear for the two windows.

**Comment by dbell154** [comment]
I thought that was by design. In practice it may be too confusing to do otherwise. 
If you could set properties in the window, and then create a new window, it uses properties from the existing window. 
If you use the main settings to configure the window all one "windows" will be changed. 
I mention this in #1735 so I would think that issue would need to be addressed at the same time if necessary.

**Comment by tuomas2** [comment]
It is by design and has been so at least since 3.3. If a user is using only 1 window (hopefully a rare case in AB users), he can control how it looks like from workspace settings.

**Comment by agrogers** [comment]
I like it if the user has only ever had one window open. It works fine.
Nice and minimal.

But what if he has changed a window setting? The workspace setting wont
affect it.

Probably doesn't affect too many people.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
You are right that this is compromising some usability to provide a bit of simplicity.

**Comment by agrogers** [comment]
Coincidentally just had this issue raised on the help desk:


Hi Andrew,


Okay, I just learned about the workspace-window distinction.  


So, yes, changing the font size within each window works fine, but if I only have one window open, meaning no split screen, and I try to change the font size, nothing changes. (See screenshot).
