### ISSUE TITLE
Bible status is updated with delay

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1977]
When scrolling, bible ref status is updated with delay. Also sync is happening with delay.
This is side effect of resolving #1879. 

Let me know do you think this is unacceptable.

**Comment by timbze** [comment]
I don't think sync delay is a big issue, but... reference update delay seems bad. 

Also, seems easy now to somehow be parked "between" verses and reference doesn't update at all until scrolling just a tiny bit.

**Comment by agrogers** [comment]
One thing that has bothered me a little is that i have had to move the
active verse to the very top of the window. It has felt at times a little
high because sometimes the top of the verse is almost off the screen. What
I think might feel better is if the active verse can be 10px or so below
the very top of the screen. Not sure if that sort of change would help this
issue - just thought i would put it out there.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
@agrogers "Top margin" window setting is a solution to that?

**Comment by agrogers** [comment]
Wow, so it is! Never set that before. Except for the gray indicator bar
it's perfect 😉

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1118

**Comment by tuomas2** [comment]
Will fix this before production.

**Comment by tuomas2** [comment]
Debouncing on Android side:

https://gist.github.com/Terenfear/a84863be501d3399889455f391eeefe5
https://stackoverflow.com/questions/50858684/kotlin-android-debounce

**Comment by tuomas2** [comment]
Fixed this.
