### ISSUE TITLE
repo down -> too long timeout

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2171]
If repository is down (right now STEP repository is), it will take few minutes until spinner stops and lets downloading. Should timeout faster.

**Comment by tuomas2** [comment]
Now total wait time of 10 seconds if one repository is not responding

**Comment by agrogers** [comment]
Good work. Is there a way to alert our user base? And let them know that it
is already fixed in the beta?

Maybe it would be a good idea to add a feature that when a user checks for
a new document or goes to the About screen, the app checks our site for
news or updates and we inform them of it. A some latest news Web page that
could be added to our docs (say) would do the job.
