### ISSUE TITLE
Figure out how to render poetic verses in NETfree

### ISSUE THREAD

**Issue by kpengboy** [AndBible/and-bible#2189]
**Describe the bug**
Forking this issue from #2183: based on my  the NETfree SWORD module appears to use `<l />` tags to denote line breaks between verses. Here is an example from Genesis 3:14:

```
$$$Genesis 3:14
The <divineName type="x-yhwh">LORD</divineName> God said to the serpent,<note os
isRef="Gen.3.14" n="36"></note> <l />"Because you have done this, <l />cursed<no
te osisRef="Gen.3.14" n="37"></note> are you above all the wild beasts <l />and 
all the living creatures of the field! <l />On your belly you will crawl<note os
isRef="Gen.3.14" n="38"></note> <l />and dust you will eat<note osisRef="Gen.3.1
4" n="39"></note> all the days of your life. <l />
```

This is contrary to the OSIS standard, which specifies that such lines should be either enclosed in pairs of `l` tags (e.g. `<l>cursed are you above all the wild beasts</l><l>and all the living creatures of the field!</l>` or use `sID` and `eID` (e.g. `<l sID="1" />cursed are you above all the wild beasts<l eID="1" /><l sID="2" />and all the living creatures of the field!<l eID="2">`, but it seems this is how NETfree is constructed and expects SWORD apps to work.

We should figure out how we might modify AndBible to deal with this technically invalid layout, perhaps by rendering an empty `<l />` as a single line break (not a paragraph break). Or maybe in theory the NETfree could be fixed to use `<l>` correctly, but I don't know if that's practically possible.

**Bug was found on And Bible version**
Version 4.0.648

**To Reproduce**
1. Download NETfree text
2. Go to a verse that includes poetry, such as Genesis 3:14
3. Notice that there are no line breaks in the poetry

**Expected behavior**
There should be line breaks where the `<l />` tag is used in the excerpt above.

**Screenshots**
| Actual | Expected |
|-|-|
| ![Actual](https://user-images.githubusercontent.com/4122890/175842654-9ee10e89-bab1-444f-aeff-d24535450490.png) |  ![Expected ](https://user-images.githubusercontent.com/4122890/175842773-2ff86955-1b0b-4d5e-b4f7-451395855aa7.png) |

**Smartphone (please complete the following information):**

 - Device: Google Pixel 6
 - OS: Android
 - Version: 12

**Comment by tuomas2** [comment]
If it's contrary to OSIS standard I think it should not be fixed here (but in the module instead). I'm afraid fixing this might break other modules. But perhaps we can take the risk of breaking (other) non-standard modules, thus fixing l-tags with no props like this: 09b6a41018ca8c72a8a3145f70a5491e8733e15c

![image](https://user-images.githubusercontent.com/5811789/179564152-fb39a6fa-bb5b-4b72-90b9-c66dea4b5010.png)

**Comment by agrogers** [comment]
I feel like AB lacks a little in the formatting of documents. I agree that these things and others should be fixed in the modules. But most likely they wont be fixed there. So the extra sparkle will need to come from the developer if we want it to sparkle. So we dont really have a choice if we want the texts to look beautiful. Beautiful text is probably more important to me than to others. Not sure how much weight it should be given. An example from MyBible (which is a great little app) which makes the formatting just that little bit nicer...

![image](https://user-images.githubusercontent.com/13920678/179936763-e9ba1716-4113-4db1-9597-271ca2e6ab7d.png)

![image](https://user-images.githubusercontent.com/13920678/179936117-77842b05-b25d-46d1-b6af-705ff9c70c94.png)

![image](https://user-images.githubusercontent.com/13920678/179936786-5766a7ca-5b6e-4e49-82ea-44f3169a95a4.png)

**Comment by tuomas2** [comment]
> I feel like AB lacks a little in the formatting of documents. I agree that these things and others should be fixed in the modules. But most likely they wont be fixed there. So the extra sparkle will need to come from the developer if we want it to sparkle. So we dont really have a choice if we want the texts to look beautiful. Beautiful text is probably more important to me than to others. Not sure how much weight it should be given. An example from MyBible (which is a great little app) which makes the formatting just that little bit nicer...

If document does not contain formatting information what can we do? I guess we could show MyBible documents as nicely as MyBible does though.
