### ISSUE TITLE
tap hold to open bookmark dialog

### ISSUE THREAD

**Issue by howdev** [AndBible/and-bible#2223]
**Is your feature request related to a problem? Please describe.**
this new one tap verse to open action dialog (or bookmark dialog) is a real frustration. You could often tap once on a verse without the intent to open the dialog. Basically you can't touch the screen unless you scroll.
Also now you cannot select multiple verses. After the dialog opens, tap next verse, the dialog closes. Then you have to click on the tiny plus sign which is not obvious to select move verse.
This one tap dialog also interferes with double tap fullscreen. Whenever double tap fullscreen, the dialog appears. Some suggested to double tap an empty area. This is very bad workaround, especially this is an app with full screen of text.

**Describe the solution you'd like**
Revert back to tap and hold to select verse or open dialog. And make the dialog fixed a the bottom of the screen.

**Describe alternatives you've considered**

**Additional context**

**Comment by agrogers** [comment]
Hi. Yes, I understand that this is a significant change to the way users interact  with the app. However we felt this inconvenience was worth it to provide new functionality.

I almost never have the problems that you are decribing and only now get the benefits. If I tap it is because i want to share the verse or add a bookmark. If i want to bookmark or share more than one verse I can still long press and drag over the range of verses that I want. Or, as you have discovered, use the plus button on the verse action dialog.  Of course tapping on a link still does what it used to do. And this still seems the most logical - generally if you tap something you expect it to do something. I think the old way was to long press to do something. I felt that was not at all intuitive for new users.

Double-tapping to enter full screen has been lost. It doesnt bother me too much because I didnt use that functionality much. I can understand that is a pain for those who do. But you can still double-tap to exit fullscreen. So it could be worse :)

Anyhow, i suggest you try it for a little while - I think you will find that it is not as bad as it might feel now and once you get used to it, might even prefer it. I would be interested to hear what others feel about this functionality too.

**Comment by howdev** [comment]
tap+hold to enter selection mode has always been the natural way, it has become natural to everyone for a long time; select files, images, videos, all items. If you want to share or bookmark a verse, a verse is an item, so it is natural to tap+hold to select, and tap more verse to select more. hold+drag is to select words, and to select the whole verse is just not natural, it is tedious. Plus the dialog has too many action items, it is just too small even on a big screen. Compare to version 3, version 4 is not simple

**Comment by howdev** [comment]
You could include an settings option to allow traditional selection method.

**Comment by timbze** [comment]
> You could include an settings option to allow traditional selection method.

From discussions we've had before, this won't happen. It would be too complex to maintain for the time and resources we have. You can always downgrade back to 3.3 if you prefer. Find the instructions for that [here](https://github.com/AndBible/and-bible/wiki/FAQ#how-do-i-downgrade-from-40-to-33).

**Comment by agrogers** [comment]
I agree that existing users may find the change a pain. But it seems most
have been OK with it and I suspect many prefer it based on the feedback or
lack of feedback.

Keeping the old way as an option is possible. But those sorts of options
increase the load on the developers to maintain two different ways of doing
things. We don't have many developers and those we do have don't have a lot
of time.

When I did some usability testing with new users who were very competent
technically, none of them found the 'hidden' long-press to bookmark feature
intuitively. That told me that the UI design could be improved. They
shouldn't need help to do something simple like bookmark.

Re the number of options, it's always a trade off between keeping things
simple and making functionality easily/quickly accessible. It seems that
the new design has been generally well received and I suspect most people
prefer it once they have got used to it.

Re bookmarking a whole verse, I think it is easier than ever. Single tap
then push Bookmark. And multiple verses also - single tap, then ➕ button. I
am sure I can do both faster now than I could before.

Always good to get feedback. Thanks.

**Comment by howdev** [comment]
as I mentioned above, long press an item is the usual way, it shows you want to do something to the item and that is what the UI of Android always been. Single tap in Android is to open something: open apps, open menu item. Longpress: is to bring up menu of actions. The changes that has been made is what certain group of people think is should work, not what the UI supposed to be. Because none of the apps like messengers, mail, gallery, music apps work this way, they all long press to take action on an item.

**Comment by timbze** [comment]
@howdev that's your opinion and liking it seems. Many apps have single press options, including other Bible apps and the very popular open source app Telegram.

You're free to take the source code and add the features you'd like.

**Comment by agrogers** [comment]
I checked You Version and Olive Tree and another app. The three of them
together have over 150 million downloads. All of them have some action for
a single tap that works like AB now works. You Version has no long tap
option at all. So I think our UI design has some good company - or at least
millions of Bible users who would agree with that design choice.
