### ISSUE TITLE
Request for full text of Peshitta

### ISSUE THREAD

**Issue by KyleBroflowski** [AndBible/and-bible#2245]
The current peshitta versions, both vocalised and consonantal are limited to just the new testament. 

Include the full Peshitta version which can be found in
https://github.com/ETCBC/peshitta

I downloaded the zip and tried to load the zip but unfortunately the Bible study app says that "SWORD module is missing"

**Comment by timbze** [comment]
Hi @KyleBroflowski, since this is a module request you can request it at [CrossWire's module tracker](https://tracker.crosswire.org/projects/MOD/issues). The AndBible team does not really work with modules.

On another note, if you find the version you need in MyBible format, you can try it out with the current experimental MyBible module support. See [this link](https://github.com/AndBible/and-bible/wiki/MyBible-module-support) for more info on MyBible modules.
