### ISSUE TITLE
Web search for highlighted keyword

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2363]
https://support.andbible.org/scp/tickets.php?id=1671

> would it be possible to add a web search shortcut to a highlighted keyword? that would be helpful!

**Comment by wesinator** [comment]
This was added in #3278. However, it seems the "Web search" menu option always opens an inline Google search app window on the latest version of Google Play Services, rather than the expected behaviour of opening a web search in a new window of the default browser app and its default search engine.

I think this is a change that Google is doing (actually on both Android at a system API hook/Play Services level, and their iOS apps with "Look Up" -> "Google search") to lock clients into using their search service.

[NO_TRAIN]::

**Comment by tuomas2** [comment]
Thanks for noting this. Will close this, but feel free to further improve this if you find a better solution.
