### ISSUE TITLE
Create new window -button almost invisible

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2381]
![image](https://user-images.githubusercontent.com/5811789/203138820-d289eb13-567e-4458-9eb7-bdc0b1c405bd.png)

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/203138924-e53d7cd7-9eac-49e9-b2d7-2053111d20f0.png)

**Comment by agrogers** [comment]
Yeah, I did that a long time ago and have thought ever since that it was
probably too hard to see.

However I very rarely use it and so it seems a shame to have something
prominent that isnt used.

Is it even needed? There are two other ways to create a new window. Do we
need a third? I feel like the best solution is to remove it altogether.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It is not visible if window buttons are hidden (isn't this the way pro users do anyway?). 
We can hide/remove it if it is not the only button.

**Comment by agrogers** [comment]
Yeah, hiding all buttons is useful too.
