### ISSUE TITLE
Tabs for multiple complete bible screen setups

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#245]
Implement chrome-like tabs, that can contain whole bible screen (including all their splitted windows) setups.

**Comment by tuomas2** [comment]
Will be implemented in build 308

**Comment by bvahedy** [comment]
Verified tabs working in 308beta. I also checked to make sure each tab carries it's own history. The only issue I have is that it takes going through 2 menus to select a tab. Other than that it's a nice addition.

**Comment by timbze** [comment]
@bvahedy You can swipe down on reference title to open tabs list. Or swipe left/right on it to jump between tabs. A bit like Google Chrome on phone works.

@tuomas2 A suggestion I would have is to possibly add Close X button at tabs list to easily close a tab. But more important for me would be to add a + somewhere to add another tab easily from there, instead of having to go to the menu to open new tab.

**Comment by bvahedy** [comment]
Nice, didn't know you can swipe from there. Much easier. Good work.

**Comment by timbze** [comment]
Thanks to Tuomas. He did all the work on this.

**Comment by bvahedy** [comment]
Well Kudos to both of you, I know you guys put a lot of work into these
mods.

**Comment by tuomas2** [comment]
Opened follow-up ticket, let's collect improvement suggestions there https://github.com/AndBible/and-bible/issues/368
