### ISSUE TITLE
Improve the way that full-screen mode is toggled (tap/double-tap/scrolling)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#262]
*Original*
Currently both tap and doubletap can be used to switch to fullscreen.
Tap seems to be standard method in Android (for example Google Docs uses it), but it is sometimes disturbing with And Bible, so enabling it should be optional (though enabled by default).

*Update 2019-02-03*
 Currently slight scrolling down and doubletap can be used to switch to fullscreen.

TODO:
- [x] If going to fullscreen by using doubletap, disable (temporarily) disabling of fullscreen mode by scrolling up (i.e. only return with doubletap)
- [x] Make scroll up/scroll down optional (three dots options menu item). Part of #269
- [x] While scrolling, we could have some transparent overlay in full screen mode showing the Book chapter:verse

**Comment by bvahedy** [comment]
Yes this is very useful as sometimes trying to bring up the hiding windows menu causes it to go into full screen.

**Comment by ericjding** [comment]
In the past, it was just double-tap; the addition of tap to activate/deactivate fullscreen must have changed recently, I guess. In any case, my experience when I first started using AndBible might be instructive: without reading the Help screen, I just dove in and started using AndBible -- but every now and then, in the course of normal operation, the toolbar on top would disappear! I couldn't figure out what had happened, so eventually, I wound up just stopping and restarting the app. It took several days before I realized I was inadvertently double-tapping when starting a swipe to scroll the page. :-)

From a usability standpoint, I think adding tap makes it even more likely that users would inadvertently switch to/from full-screen mode, so my first instinct is to actually suggest reverting to the old behavior.  There are too many instances where tap can inadvertently be triggered: drag to select, swipe to scroll, etc., and adding one more setting for a feature that's inessential or even unhelpful seems like adding more noise.

But if you _really_ want to keep "tap to toggle full-screen mode", then may I suggest, instead of adding an option to only use double-tap, an alternative: What if the feature allowed the user to choose between three options instead? That is, in order to switch to/from full-screen mode, the user can choose between (1) tap, (2) double-tap, and (3) turning off the feature altogether. The third option would allow users to avoid even the accidental double-tap to toggle full-screen.

**Comment by Autofire** [comment]
On a tiny screen, I will say that full-screen is a nice feature. I wouldn't mind having it auto-hide after scrolling some distance, and then able to bring back with a single tap. This, of course, would be optional.

If I get the time, I'll clone the code and see if I can implement this myself. I like to try giving fullscreen mode its own dedicated area in the options screen, or at least having associated options. So it might have this:

- [ ] Enable Fullscreen
  - Double Tap _(dropdown which could be swapped to Single Tap)_
  - [ ] Autohide when scrolling

The other two options grey out while fullscreen is disabled.

**Comment by tuomas2** [comment]
@Autofire please do! :) I'll invite you to Contributors team.

**Comment by tuomas2** [comment]
I thought that @Autofire 's suggestion was worth trying. I kind of like it as a default behavior for now. Let's try it in beta channel (releasing tonight new beta).

**Comment by tuomas2** [comment]
Please let me know what you think about the new version which is now released in beta channel (3.0.287).

**Comment by bvahedy** [comment]
I'm find with it, let's give it a try and see how it goes.

**Comment by tuomas2** [comment]
> I would like to see the floating button disappear unless needed, frankly, but I know we've already got a separate issue related to a similar request. But at the very least, I think the floating button should hide immediately (rather than after a delay) along with the status/nav bars when full screen mode is triggered by downward scrolling. (-> #246)

This can be discussed on #246. 

> For triggering full-screen automatically when scrolling downward, the distance should not be in pixels, but in some real-world distance (e.g., 1cm) or percentage of screen height, so that the behavior is roughly equivalent across devices of different resolution. The equivalent in pixels should be pre-calculated and stored in a constant, of course, so that it's not re-calculated everytime onScroll() is called.

This is how it is right now (net.bible.android.view.activity.page.BibleGestureListener#scaledMinimumFullScreenScrollDistance)

**Comment by bvahedy** [comment]
Eric, 
I had initially suggested the same thing to Tuomas but I like what he did.
Currently if you enter a full screen it only takes a slight scroll downward to bring up the menu bar or you could use a double tap.  I feel we lose more flexibility by forcing  a double tap  to get out of full screen mode.
Let's play with it a bit longer and also wait for some more user feedbacks and go from there.

Regards,
Ben

**Comment by ericjding** [comment]
@bvahedy I really like what @tuomas2  did too, and I'm not suggesting we undo it -- what I'm saying is that if a user __deliberately_ enters full-screen mode with a double-tap, it's not unreasonable to assume they want to **stay** in full-screen mode even if scrolling backward (that was the case for me this morning). So in that particular case, AB should perhaps not exit full-screen mode in response to scrolling backward.

While I'm at it, I'll make another complementary (not alternative) suggestion: make the backward scroll to exit full-screen mode less sensitive than the forward scroll to enter full-screen mode. I may scroll backward just a bit while searching for something in the text, but not want to exit full-screen mode as readily as I enter when scrolling forward.

**Comment by bvahedy** [comment]
Eric,

I like your idea of making backward scroll less sensitive. In the current
release if you scroll down/backward slowly you won't exit full screen, but
I guess you want it much less sensetive.  we need to consult with Tuomas as
to how much work that would be. I guess for me it's easier to scroll than
to double tap to enter or exit full screen mode.

Ben

**Comment by tuomas2** [comment]
Now best ideas should be implemented. (will be in next beta). If you think I missed something, please create a new feature request ticket.
