### ISSUE TITLE
Jump to X (where x is reference that is copied to clipboard)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2935]
- Add new menu item "Jump to X" into window button dropdown menu, where X is the reference that is copied into clipboard.
  - For example: Jump to Gen 1:1, Jump to Studypad X, Jump to Kingcomments: Gen 1:1
- If there is no reference copied into clipboard, hide menu item
- Feature will be implemented primarily for Bible references. If there's enough time left in budget it will also support other document types.
- This works for references that are copied in AndBible's link format, i.e. from Window Button menu -> "Copy reference to clipboard".

Time estimate: 1 hours of work.

Related: #687

**Comment by agrogers** [comment]
I am not sure the name of the document is needed in the menu entry since the button you are using to 'paste' the reference is the window button for that document.

I think "Jump to xxx" is better that "Paste xxx".

Does the long-press on a ref link (say in the TSK) use the same format as the copy menu option? If so, that copy option should also affect the "Jump to xxx" menu option.

**Comment by tuomas2** [comment]
It now has "Go to X" menu entry in window menu if a link has been copied earlier from AndBible. It does not work if link is copied from another app. I can implement that too if it is needed, but I believe normally this is enough.

**Comment by agrogers** [comment]
Works well. Thank you.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
