### ISSUE TITLE
If long bible reference does not fit, use abbreviation

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#302]
With small screens, there might be unreadable abbreviations like Deuteronomy 32:5 -> De... 2:5. We could fix this by showing only abbreviated version of reference if the full reference does not fit.

**Comment by mattzab** [comment]
Why not use abbreviations at all times? Older version did so, and still displayed the verse number there, making it easy to find a verse quickly.

Full book names hide verse numbers in newer versions, so scrolling quickly to a verse is impossible. "The Revela" might display, but it was much more convenient to see "REV 2:4" when scrolling, to easily see the verse. Particularly useful in long chapters like Ps 119

**Comment by timbze** [comment]
I tried separating the reference name from the chapter:verse, so that the chapter:verse would always show completely and then just cut the end of the reference name, but I can not get it to work.
My suggestion is like @mattzab to just switch back to only using short references, for now.

Here's patch file of what I tried. I also tried with RelativeLayout and ConstraintLayout to no avail.
[0001-shorter-ref-name.txt](https://github.com/AndBible/and-bible/files/3726351/0001-shorter-ref-name.txt)
