### ISSUE TITLE
Check slf4j dependencies 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3174]
https://github.com/AndBible/jsword/pull/14#issuecomment-1898020952

- Check if de.psdev.slf4j-android-logger is coming from some other lib transitively. 
- Write explicit dependency for it in jsword dependency specification.

**Comment by tuomas2** [comment]
Can you @UnasZole check if  309941d looks correct.

**Comment by UnasZole** [comment]
It seems ok, but why do you exclude("org.slf4j:slf4j-api") ?

slf4j-api is the interface of the logging system.
JSword depends on it because it calls the loggers.
slf4j-android-logger also depends on it because it provides android implementations for these loggers.
So in any case, your application contains slf4j-api, otherwise everything would break.

The only thing your "exclude" does is to force Gradle to take the version of slf4j that is brought transitively by slf4j-android-logger instead of the one from jsword - but in any case, it shouldn't make a difference as far as I know.

**Comment by tuomas2** [comment]
> It seems ok, but why do you exclude("org.slf4j:slf4j-api") ?
> 
> slf4j-api is the interface of the logging system. JSword depends on it because it calls the loggers. slf4j-android-logger also depends on it because it provides android implementations for these loggers. So in any case, your application contains slf4j-api, otherwise everything would break.
> 
> The only thing your "exclude" does is to force Gradle to take the version of slf4j that is brought transitively by slf4j-android-logger instead of the one from jsword - but in any case, it shouldn't make a difference as far as I know.

Thank you for this explanation! Removed exclusion in bb0798f62ac5bd8289d59bedd090ba8d666ef9e4
