### ISSUE TITLE
Bookmark / scrolling issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#324]
To reproduce: 
(Note: this bug does not happen consistently)
1) open  two windows. 
2) make sure win. synch is checked.
3) for the bottom window choose a Bible that only has old testament, e. g. JPS
4) from bookmarks go to a passage in the OT, both windows match.
5) again go to the bookmarks and  choose a passage from the NT. So far all should be good.
6) from bookmarks go to a passage in OT.
Check the book/verse ref. on the menu bar. It is incorrect. They will not mach the passage from the bookmark. If you don't see this issue keep going to diff. passages from your bookmark and it eventually happens. Don't really know exactly want triggers this issue and it's not consistent. 

From play store beta feedback:
> One problem I have noticed now is that if I am reading consecutive chapters and make a bookmark in the second chapter, when I go back, I end up in the first chapter and have to scroll back down to the second chapter. I then just went to the second chapter and just got skipped back to the first one I read.

**Comment by tuomas2** [comment]
@bvahedy can you check if you can reproduce?

**Comment by tuomas2** [comment]
I can't reproduce, but I'm not sure if I understood this report correctly.

**Comment by bvahedy** [comment]
I need more info on this. Is he talking about speech reading or Just scrolling down?

**Comment by tuomas2** [comment]
I'm hoping he will send email or comment on this ticket.

**Comment by tuomas2** [comment]
Whole message was:

> One problem I have noticed now is that if I am reading consecutive chapters and make a bookmark in the second chapter, when I go back, I end up in the first chapter and have to scroll back down to the second chapter. I then just went to the second chapter and just got skipped back to the first one I read. Is it possible to not have the continuous scroll and to just be able to swipe left or right for the previous or next chapter?

**Comment by tuomas2** [comment]
This ticket can be waiting here until 3.2, but if we don't get more information, it will be closed.

**Comment by ylin2slbcom** [comment]
i have a similar issue.

say i have two different book marks,
BM1. Deuteronomy 8:2
BM2. John 11:4

if i pick BM1, it jumps correctly.
then i pick BM2, it jumps correctly as well.
and then pick BM1 again, it jumps to John 8:3 instead of John 11:4.

switching these two bookmarks repeatedly, you will see these often, but not all the time.

**Comment by bvahedy** [comment]
I'm unable to recreate the problem, Please clear your Andbible cache from
the device settings and see if this issue goes away. The other alternative
is to do a fresh install.

**Comment by ylin2slbcom** [comment]
i just find out that you need to have split window on.

**Comment by bvahedy** [comment]
Do you mean window synchronization?
If so, Andbible is functioning correctly when window synch is unchecked,
for then each window can be at a different passage.

**Comment by ylin2slbcom** [comment]
yes, window synchronization.

and, i understand each window can display different chapter.

this is clearly a bug, since, i could end up with Hebrews 99:9 in the attached screenshot.

i have six BMs
BM1 Proverbs 14:27
BM2 Deuteronomy 9:1
BM3 Hebrews 10:35
BM4 John 12:46
BM5 Psamls 98:1
BM6 2 Corinthians 8:5

just switching BM back and forth, you will encounter from time to time, NOT all the time.
![Screenshot_20190312-105052](https://user-images.githubusercontent.com/18427489/54215223-93be4380-44b5-11e9-8566-16af4ed348be.png)

**Comment by ylin2slbcom** [comment]
i set the other window with a different version. i do have Synchronise checkbox checked.

**Comment by bvahedy** [comment]
Ok, I can say it now. I have created a bug ticket for this:
https://github.com/AndBible/and-bible/issues/336

**Comment by bvahedy** [comment]
I think what is happening is that when the lower window has no New Testament books and the top window does, upon the top window going back to an OT passage the lower window loses its synchronization and also messes up the chapter vs ref. In the menu bar heading.

**Comment by ylin2slbcom** [comment]
before it was messed up, both windows has New Testament.

**Comment by timbze** [comment]
@tuomas2 Maybe you can help with this when you have time. I already know that this is a thread race, that's why it happens off and on, and probably happens more often in faster phones. The reason I believe it happens more on faster phones is because on emulator I was able to reproduce once in a while, but on my LG G6 it happens almost every time. All I need to do is select a bookmark and it goes to a wrong passage, even with just a single window.

**What happens in the code**
In BibleJavascriptInterface.java, clearVersePositionsCache() needs to be called before onScroll(). Every time this order is correct, it works. But every time the order is reversed, it tries to go to a wrong passage. The reason is that the verseCalculator needs to be cleared by calling init(), and if onScroll() gets called before that happens then the verseCalculator.calculateCurrentVerse() uses the Y point of the previous loaded passage rather than the new passage being loaded now

**How to proved it's a thread race**
In BibleView.kt, change onLoadResource to add a thread.sleep, like this:

```
override fun onLoadResource(view: WebView, url: String) {
    Log.d(TAG, "onLoadResource:$url")
    Thread.sleep(500L)
    super.onLoadResource(view, url)
}
```

Or, instead of doing that just put a breakpoint on the Log.d line (so that you have to continue when it gets there), and the issue never happens

This issue is so weird, because the code does close to the same thing as just picking a passage from Choose Book/Chapter/Verse screen. And using the book/chapter/verse picker, this issue never happens.

**Comment by timbze** [comment]
Well I had this happen to me the first time now when just going to a passage from Book/Chapter picker. AB is on Matt 7:17 KJV, only one window open (4 workspaces and I'm on the last one). I select John 10 from Book/Chapter picker, and it goes there, but then shows John 7:1 in title bar.

**Comment by timbze** [comment]
One further revelation :). It seems when I uncheck "Show bookmarks" under "Bible text options" it never happens. As soon as I check it I get it more frequently now. It may happen more frequently when navigating to a chapter with more bookmarks. I have 2 bookmarks in John chapter 10 (v27 and v30) and when I go to Daniel 3:12 then go to John 10 from there, it jumps to John 10, then title jumps to 3:1
Or if I'm at Matt 7:17 then go to John 10, it navigates to John 10 then title jumps to John 7:1.

It may work to add a bunch of bookmarks to a chapter and then just try navigating there from some other place. It seems to happen more often when starting from a verse greater than 1. For example, Daniel 3:3 or Matt 7:3, then navigate to John 10. Not from 3:1 or 7:1.

**Comment by bvahedy** [comment]
Tim, I'm not able to duplicate what you are experiencing but  I did
experience the title being wrong when I  tapped on a strong word and went
to show all occurrences then selecting from a from a search list, when I
tried going back to the original verse using the device's back button I
noticed the book title was incorrect.

**Comment by tuomas2** [comment]
I made today some related work / fixing with js interface and seems that this issue does not occur any more (even with Thread.sleep as suggested by @timbze ). However, please test manually if it is fixed or not.

Will be fixed in build 315

**Comment by timbze** [comment]
Issue is still happening :man_facepalming: 

This is build 315
https://photos.app.goo.gl/Ff86GwNDjYLQ42979

**Comment by bvahedy** [comment]
I'm unable to reproduce this thus far, will keep an eye on this.

**Comment by timbze** [comment]
This only happens when "Show Bookmarks" is on under "Bible Options"

**Comment by bvahedy** [comment]
Yes, I had it checked, I have tried numerous ways, it's still not
happening. I have seen these issues occur when I don't do a fresh install.
I know it's a pain but since you can reproduce this issue, is there any
chance you would be willing to do a fresh install and see if it's still
happening.

**Comment by timbze** [comment]
I checked now and it happens on my phone after a fresh install too.

**Comment by bvahedy** [comment]
Thanks for trying, I'll keep an eye on this bug.

**Comment by tuomas2** [comment]
@timbze could you please obtain logcat report when you reproduce this bug?

**Comment by timbze** [comment]
@tuomas2 Here you go
[bookmark-NOT-working.txt](https://github.com/AndBible/and-bible/files/3800791/bookmark-NOT-working.txt)
[bookmark-working.txt](https://github.com/AndBible/and-bible/files/3800792/bookmark-working.txt)

**Comment by tuomas2** [comment]
Attempted to fix again (build 317). Let's see.

**Comment by bvahedy** [comment]
In build 316, I tried minimizing a third window, and then tapping on the middle window which is jps, I went to a bookmark in Genesis and the top window went to the wrong chapter. See the snap shot attached. This happens also if you close a third window. 
![Screenshot_20191113-110913_And Bible](https://user-images.githubusercontent.com/46405809/68796796-509a0e80-0608-11ea-9a5e-93b0da2de888.jpg)

**Comment by bvahedy** [comment]
In beta build 318 this issue still occurs where if you minimize or open or restore a third window and try to navigate to a bookmark the title is not the same as the bookmark or the windows passages are not synched on the same verse.

**Comment by tuomas2** [comment]
Again, might be fixed in 318.3. Tried to reproduce this

> In build 316, I tried minimizing a third window, and then tapping on the middle window which is jps, I went to a bookmark in Genesis and the top window went to the wrong chapter. See the snap shot attached. This happens also if you close a third window.

and could not.

**Comment by tuomas2** [comment]
Please re-check this with 318.3.

**Comment by bvahedy** [comment]
This seems to be fixed in build 319.1

**Comment by tuomas2** [comment]
I'd like to hear from @timbze still if he can reproduce this.

**Comment by timbze** [comment]
It is fixed!!! Thank you @tuomas2 !
