### ISSUE TITLE
App crashes when a bible module in one of the tabs is deleted... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#375]
**Describe the bug**
AB crashes when a bible module in one of the tabs that is not in view is deleted.

**To Reproduce**
Create two tabs with two windows in each tab. first tab should have kjv and esv. For second tab use kjv,  jps
1) From the first tab, tap and hold Bible chapter, on the top left on the menu bar.
2) from the list of Bibles tap and hold JPS, then from top left of menu tap on the delete icon.
3) try to switch to second tab which use to contain jps module, the app crashes.

**Expected behavior**
Needs to be discussed.

**Comment by tuomas2** [comment]
Expected behavior: if module is deleted, window should disappear also from any tabs it was opened.

**Comment by timbze** [comment]
Another similar scenario, not giving crash though.

1. Just have 1 window open with one Bible version.
2. Delete the document currently open
3. It's still showing the deleted document, but as you scroll up or down the next and previous chapters load in another document that still exists.

**Expected Behavior**
I think the active document should switch to available document after it gets deleted.

**Comment by timbze** [comment]
> Expected behavior: if module is deleted, window should disappear also from any tabs it was opened.

AB knows how to handle when module has been deleted, the issue that is here is because of tab history. AB has up to this point just selected first available Bible if the active one has been removed, and not closed the window. To keep things consistent with other things that might happen, I suggest that would be better.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Verified fixed in 312.
