### ISSUE TITLE
Beta notice popup to Beta users

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#387]
I would like beta users know that they are beta testing a possibly non-stable release.
Popup notification which is shown once after each (beta) update is one possibility (with option to stop seeing those messages). Probably separate menu entry as well to main menu which shows the same info (which is visible to beta users only). Notification would say what beta testing means and also tell how to stop beta testing and use stable version instead.

How to distinquish beta version? I could start adding -beta to versionName in AndroidManifest.xml.

**Comment by tuomas2** [comment]
@timbze what do you think about the idea?

**Comment by cmahte** [comment]
The updates are when it's important. I'm on the beta channel, but the
updates don't show beta in large letters, and updates happen without my
involvement.  Beta software should always ASK to update, and warn it's
beta, and hopefully provide some kind of details on what's going to be
different.

I know some of that is in the Android settings, not under andbible control,
but if you're thinking about changing it... focusing on the install and
updates is where beta announcements are important, not every start.  I know
what I've installed. but remind me when the code is changing.

**Comment by tuomas2** [comment]
@cmahte Automatic updates can be disabled in Google Play settings.

**Comment by cmahte** [comment]
The setting moves around from device to device, and versions of android.
The problem is that I have one primary google account shared across usually
5 or 6 android devices, but scrub and refresh different devices, as
projects and trips require. The option to manually update seems to be
required on every device for each program, but the option to auto update
seems to propogate from one device to another.  So every time I log in to a
device, I have to remember to go back and unselect all the auto updates on
each device I'm currently using (This is not a tested condition, just my
perceptions of my experience.)

The fact that alpha channel and beta channel Play store apps also do
this... again this is an Android issue, not a AndBible issue.

This behavior isn't 100% (motorola devices act differently than samsung
devices act differently than amazon devices act differently than nikon
devices act differently than virtual machines. but they all want to install
all my apps from a backup somewhere during first install (Google,
manufacturer, or phone company backup) and that may start the auto updates
everywhere all over again.

**Comment by timbze** [comment]
I think this would be a great idea. I think there should be 1 popup when beta for 3.2 starts, but subsequent beta updates before 3.2 probably wouldn't need any further popups, since it's mostly stabilizing the version.

And I think there should be another menu item that would show the same beta information, and possibly also an easier way from there to submit a bug report.

As per @cmahte concern. I think those who sign up for beta should do it knowing that the beta updates will be automatic, unless the automatic updates are disabled from Play Store. As you said, this is really an Android issue. We could think of having a completely different system for beta to do it a bit more like you suggest, but I don't think it makes sense for us to do that.

**Comment by tuomas2** [comment]
This is what I implemented:

![Screenshot_1570701819](https://user-images.githubusercontent.com/5811789/66559708-8148dd00-eb5e-11e9-9c8d-c361cab14866.png)

**Comment by bvahedy** [comment]
Is it possible to add the beta version somewhere on this pop up window?

**Comment by tuomas2** [comment]
You mean simply version number? Yes, I can add it. It's visible also in help screen.

**Comment by bvahedy** [comment]
Yes, I know it's on the help screen, but it's a good verification to see
just the version no. On this pop up.
Not a big deal if it's a lot of work.

**Comment by bvahedy** [comment]
Verified fixed in build 315.
