### ISSUE TITLE
Add a way to add custom document repositories

### ISSUE THREAD

**Issue by nikaro** [AndBible/and-bible#39]
Hello. It should be nice to have the ability to add other repos than the hardcoded ones.

Updates from @tuomas2:
 - Show SWORD MRL (master repository list) repositories automatically.

**Comment by g4jc** [comment]
I second this. I actually keep a locally cached copy to avoid re-downloading the same books over and over, however I'm unable to add it to the hardcoded file without re-compiling the program.
https://github.com/mjdenham/and-bible/blob/595e5bfe671b482ec0a1d8f16d6fbe52229b730c/jsword-tweaks/src/main/resources/InstallManager.plugin

**Comment by g4jc** [comment]
I found one work around, per: https://groups.google.com/forum/?_escaped_fragment_=topic/and-bible/hcrgU_Eqkuk#!topic/and-bible/hcrgU_Eqkuk

1) Mirror your favorite repo: wget -r --no-parent --reject "index.html*" http://path.to.some.repos/
(e.g. ftp.xiphos.org/pub/sword/)

Then on the Android's sdcard -  usingTerminal Emulator or Ghost Commander: 
cp modules and mods.d directories to /storage/sdcard0/jsword

When you boot AndBible the offline books work! :+1:

**Comment by nikaro** [comment]
Thanks for the tips :+1:

**Comment by mjdenham** [comment]
Another way would be to store the zips somewhere on your network and use And Bible's new 'Install from Zip' feature.

Btw which repos and modules do you use that aren't already available.  My aim is to make everything that is most useful readily available in the simplest way.

**Comment by g4jc** [comment]
My biggest reason for wanting the feature was to load the Xiphos bible and dictionary modules from WLAN onto several different android devices. Since I have a slow internet it would save my a considerable amount of time. I'm not that sure those modules are in zip format? 

Thanks.

**Comment by ildar** [comment]
Guys, I don't feel this feature request to be finished. There should be a
way to add custom repos. I agree that typing isn't the most fun way to do
it. Then some container format could be used.
Reopen?

**Comment by johndudeck** [comment]
Greetings. I am just getting involved with module development for AndBible.

I am involved with a project to create a set of French Bible study materials for French-speaking African pastors. There are potentially more than a hundred modules that may make up this library. Many of them are not public domain and are used by permission of the publishers for distribution in this project.

 We have selected Sword and AndBible for our platform, primarily because it can be deployed and updated completely off-line. On the other hand, for those users who have connectivity, it would be valuable for them to update their modules online, which is far simpler than sending microSD chips to the African bush. We may do that, too, but the online option is important to us.

I have set up a private repository, and am able to access it from Xiphos Module Manager. But I would like to have a way to access it from AndBible.

So this is a potential use case for adding a feature for setting custom repositories in addition to the existing list.

**Comment by agrogers** [comment]
Hi @johndudeck. Are you still working with African pastors? And do they still use And Bible?

**Comment by johndudeck** [comment]
Andrew,


Yes, I am still working with the project of French content for AndBible for African pastors. The organization that I work with is 
partnering with another organization that is supposed to be handling the distribution. However I don't have any current updates on 
how well the distribution is going. I suspect it hasn't really taken off very well yet.


John







Hi 
@johndudeck. Are you still working with African pastors? And do they still use And Bible?

—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 

unsubscribe.


John Dudeck              Tel: +1-704-588-9891  Cell: +1-803-504-8065

***@***.***                        Charlotte, North Carolina

--

"There are no shortcuts to anyplace worth going." -- Beverly Sills

**Comment by agrogers** [comment]
Thanks for the update John. I was interested to know easy to use the pastors found And Bible. I don't know of any better Bible study app the AB. But it's features make it considerably more complex than some alternatives. Do you have any comments on that?

**Comment by johndudeck** [comment]
Andrew,


I do not have any doubt of the ability of African pastors to figure out the fine points of AndBible. The Africans that I have known are 
by nature very clever. It is my opinion that the materials should be distributed by means of training seminars that will get them up to 
speed from the outset. Another means would be for it to be spread through the Bible schools across Africa.


Any pastor that is motivated enough to study the Bible should be able to benefit greatly from the availability of Bibles, 
commentaries, and dictionaries on AndBible. Having fifty such books available on his Android device should keep him occupied for 
a long time just exploring. I have not yet heard any feedback from Africa per se.


Since Tuomas has assumed development responsibility for AndBible he has made a lot of improvements that make it even more 
usable. I am still hoping for one-touch lookup of words in a dictionary (beyond Strong's numbers), and for interlinear bibles.


John







Thanks for the update John. I was interested to know easy to use the pastors found And Bible. I don't know of any better Bible 
study app the AB. But it's features make it considerably more complex than some alternatives. Do you have any comments on 
that?

—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 

unsubscribe.





John Dudeck

Programmer at Editions Cle                             Lyon, France

***@***.***                            ***@***.***

--

It seems the height of arrogance that someone would suggest that the Creator 

should not take an active role in creating His creation, merely because I am 

unable to understand how He did it.

**Comment by tuomas2** [comment]
Related #2487
