### ISSUE TITLE
After some usage, cannot change documents anymore

### ISSUE THREAD

**Issue by ldutra** [AndBible/and-bible#391]
In Moto Z² Play with a French interface, specifically MorphGNT and Real Strong’s, the β release ceases being able to change documents.  One can select other Bible texts but the text itself does not change.

To reproduce:
Note: in the setting the "open links in spec window" must be checked.
1) Show Strongs numbers in some version of Bible and click a Strongs link, Special window opens,
2) scroll in Special window (dictionary definition window) so that it is active and has a click X button to close but Do not touch the active Bible window 
3) from the top menu bar try to change to another Bible version, and it's not changing.

Side note: In this bug I found, once you touch the active window to scroll or something, you can change document again.

**Comment by timbze** [comment]
Hi @ldutra, have you come across this issue more than once? Could you give us the exact steps in how to reproduce the issue?

**Comment by ldutra** [comment]
Yes, at least thrice in so many weeks.  I did not fathom a precise sequence, but it seems to me to happen after I consult a Real Greek Strong definition from MorphGNT.  Does this help?  Is there anything else I can do to gather more info?

**Comment by timbze** [comment]
I think I have found the issue. I will submit a PR for fix soon

**Comment by ldutra** [comment]
Thanks a lot!

**Comment by timbze** [comment]
For bug fix tester: 
**To reproduce:**
1. Show Strongs numbers in some version of Bible and click a Strongs link
2. Special window opens, scroll in Special window (dictionary definition window) so that it is active and click X button to close.
3. Do not touch the active Bible window now, instead try to change the active document to another Bible version or something, and it's not changing.

Side note: In this bug I found, once you touch the active window to scroll or something, you can change document again.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Verified fixed in 312.
