### ISSUE TITLE
Bible reference lookup in other applications (text fields)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#429]
How this should work.

1. Open Google Docs (or any text field anywhere)
2. Write some text there, and include bible references, like Matt 1:10.
3. Long-click bible reference and adjust selection so that whole reference is selected
4. And Bible should inject "Verse lookup" to the context menu, similarly as Google Translate does "Translate".
5. Verse lookup opens a small popup window that shows chosen bible verse, or alternatively jumps to And Bible directly, which selected verse opened.

**Comment by tuomas2** [comment]
Also "Go to reference from clipboard" might be useful action from menu. Or maybe not.. let's see.

**Comment by timbze** [comment]
Related: #232

**Comment by tuomas2** [comment]
Similarly, we could allow user easily to access search entire bible content via similar menu item.

**Comment by mcepl** [comment]
Well, I would be interested in the access from the web pages.

I have SPA https://hesla.ceplovi.cz which displays [Daily Watchwords](https://en.wikipedia.org/wiki/Daily_Watchwords) (unfortunately I have only Czech and German texts, if anybody knows somebody in [Moravian Church](https://www.moravian.org/the-daily-texts/) who would be willing to share the texts for non-commercial use, I am all ears). Every daily reading has reference to the original Biblical verse, so it may be read in the context. Unfortunately, right now I have to link to https://www.crosswire.org/study/, because I don’t want to link to texts outside of Crosswire realm (yes, I know about https://ref.ly and https://bib.ly), and that webpage is really crappy for reading on the mobile phone.

I would a way prefer if I could add [link like](https://github.com/Verses/Common_Bible_Share_Sheet) ``bible://?passages=[Gen.1.1-Gen.1.4,Gen1.8]&translation=CzeCSP&intention="Read"`` (or even with the scheme ``bible-andbible``) and after clicking AndBible would open with the appropriate verses shown.

**Comment by agrogers** [comment]
Some interesting ideas there. My initial thought on this is to enable the Share option on mobile devices for highlighted text. AndBible then parses that received text looking for a verse reference and shows it. Perhaps if there is no verse reference found it opens the Search window for a bible search. 

https://drive.google.com/file/d/17YwJkEkwyFcytTeTcsjLlVfm94hkXtp1/view?usp=drivesdk

**Comment by tuomas2** [comment]
Related #1215 #1044.
Key to this feature is PROCESS_TEXT intent.

**Comment by tuomas2** [comment]
possibly related https://support.andbible.org/scp/tickets.php?id=1660

**Comment by tuomas2** [comment]
implemented
