### ISSUE TITLE
Can't restore backup from SD storage

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#461]
@rik-shaw wrote:

> I am having this trouble with a new install of LineageOS 16 (Android 9, "Pie" based). When restoring, it gives an error saying "An error has occurred". Is there any more detailed log available? It could be that I am using a sd card formatted as internal storage. I could try by re-formatting as external storage and only using the internal storage.
> 
> I hope I can restore the bookmarks: it is years worth of effort I don't want to lose. I unfortunately did not do a full backup of the app folder, I only have the andbible_backup folder :-(

**Comment by tuomas2** [comment]
@rik-shaw Do you have andBibleDatabase.db in andbible_backup folder? Could you provide your backup file here?
With adb logcat you could provide extra info what's going on.

**Comment by rik-shaw** [comment]
My bookmarks aren't private so I am happy to provide them. I'll need to wait to get home tonight to try again. Do I just run something like "adb logcat > log.txt" while then trying through the phone interface to restore? I am on linux if it helps but not too experienced in Android debugging.


[andBibleDatabase.db.zip](https://github.com/AndBible/and-bible/files/3939815/andBibleDatabase.db.zip)

**Comment by tuomas2** [comment]
Which version of And Bible are you trying to use? Latest stable 3.1.305 or latest beta (3.1.319.4)?
Yes, in principally you start app, and before running action that causes error, you start adb logcat > log.txt, and when error occurs, you stop logcat with ctrl-c.

**Comment by tuomas2** [comment]
Tried restoring db file with my current development version and seems to load OK.

**Comment by rik-shaw** [comment]
I reformatted my sd card as "portable storage." This uninstalled And Bible since it must have been installed to the sd card so I re-installed. I then copied the backup to the root of the internal storage, and restore from backup worked without issues.

So I think the possible "bug" is that when using a sd card as part of "internal storage." Anyway, I would think this bug could be closed as I have restored my backup, but you may want to keep open if you want to investigate further.

**Comment by bvahedy** [comment]
This is working in 320.1 beta. I am guessing the user may not have given
permission to read/write the SD card.
