### ISSUE TITLE
Share bible verse options

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#506]
Share options:

- [x] - Text with verse numbers
- [x] - Text without verse numbers
- [ ] - Share just references
- [ ] - Share verse list as text (to bookmarks)

I think this should be implemented as a popup menu after clicking "Share" in verse selection mode.

**Comment by mmm4m5m** [comment]
I would like to share the verse with additional details. Probably I will choose full details:
1. book name, chapter and verse numbers, verse text
2. document name with short description and short note - how to download the document.

**Comment by agrogers** [comment]
So many feature requests! I use this feature a bit in Esword pc version. It allows to put verse references at the start, at the end, put all verses in paragraph or line by line format and others.

Perhaps the only 'bug' I've noticed recently is that sometimes when I paste a verse the book name is shown abbreviated and other times it is not. I haven't looked into this because it is not an issue. Just unusual.

**Comment by tuomas2** [comment]
Closing this, as most important parts are now implemented. New issues can be created for missing parts (if someone really misses something that was not implemented).
