### ISSUE TITLE
The 'Rebuild Index' split across two lines 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#700]
Hi 

This is perhaps similar to the other display issue I raised. Although this one is not wrong, just a little messy. It looks to me like you expected it to be on a single line.

![Screenshot_2020-06-06-07-44-00-863_net bible android activity JJK](https://user-images.githubusercontent.com/13920678/83925141-c85ca000-a7c9-11ea-83a5-611d46170201.jpg)

Cheers 
Andrew

**Comment by bvahedy** [comment]
Andrew,
I believe it's suppose to be this way, since it helps to tap on it as a
group of words. There are three options on that line, if it was separated
by a space it would look like four options.
When dealing with databases, rebuild and index are two separate thing.
Having it on two lines as it is now tells the user that it is just to
rebuild the index.

Ben

**Comment by agrogers** [comment]
Ah, fair enough. Maybe that it is not centered made me think something was
amiss.

Thanks for the explanation - there are bigger fish for you to fry i'm sure
:)

**Comment by tuomas2** [comment]
looks ok to me
