### ISSUE TITLE
Strongs dictionaries do not contain suffixed keys

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#750]
And Bible user reported:
> Issue with NASB module
> 
> 1. Clicked on several Strong's numbers with an 'a' suffix
> 2. Always linked to 8674
> 3. Numbers with a b suffix worked fine
>  
> An example would be 2 Kings 25:27, for the words 'king' (4427a) and 'kindly' (2899b), both link to 8674.
> 
> I use NASB and Strongs Real Greek/Hebrew. I downloaded a diff set of Strongs before with the same results.

**Comment by tuomas2** [comment]
Moved from https://tracker.crosswire.org/browse/MOD-377

**Comment by tuomas2** [comment]
Need to check if our strongs modules are outdated.

**Comment by bvahedy** [comment]
Strong numbers in the dictionary do not contain any suffix.  I think those
are footnote ref. That are mistakingly placed in the Strong's tags in the
NASB module. So it will fail because it's trying to look up 4427a and it
doesn't exist in the dictionary.  This is a NASB module issue and not the
dictionary.

**Comment by tuomas2** [comment]
Please see comments on https://tracker.crosswire.org/browse/MOD-377. I need to check the problem and decide next step anyway.

**Comment by bvahedy** [comment]
I guess you can strip any alpha letters from the right side of the string programmatically and just pass the Strong's no. through for search.

**Comment by timbze** [comment]
A little testing with diatheke and Xiphos brought me to this:

Searching 4427 or 4427a works, but searching with H prefix, H4427 or H4227a always returns 8674. Even H3605 or any other number, **if search is submitted with 'H' prefix, 8674 is returned**.

**Comment by tuomas2** [comment]
Removing suffixes as @bvahedy suggested. Will be fixed in build 384

**Comment by tuomas2** [comment]
Weird default this 8674 though. I would wish returning null or something if not found.

**Comment by bvahedy** [comment]
That's because of a bug in the dictionary. I get a not found when the no.
Isn't found.
Can you try replacing these files on your device and see if it corrects the
issue.
There is a readme file, take a look at that first.

https://1drv.ms/f/s!AgQrBUWnj0-jgjgC8i1RyunP6hnv


This will also give you two combined dictionary definition for words
instead of just the Strong's.

**Comment by bvahedy** [comment]
Verified fixed in build 384.
