### ISSUE TITLE
Bookmarking popup improvements

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#859]
After creating a bookmark, a popup (snag bar) appears, allowing user to click 'assing label'.
In this popup, the there could be a button to choose one of most recently used bookmarks quickly.

**Comment by tuomas2** [comment]
Kindle has 4 different colors to choose from, easily accessible. We could have something similar (configurable shortcut labels)

**Comment by agrogers** [comment]
Hi Tuomas. Are you referring to this little standard android popup menu?
![image](https://user-images.githubusercontent.com/13920678/116842904-8d552d80-ac21-11eb-9b7b-1e7b12c466ed.png)

What I would like to add to this popup is:
* 'Bookmark Verse'.  This would apply the bookmark to the whole verse for me automatically 
* And perhaps show the last two or three used labels so the bookmark with that label could be applied directly. I am not sure if that is what you meant above or whether you meant adding an additional label to an existing bookmark. I tend to add multiple bookmarks to the same word since i want to the bookmark to be visible.

**Comment by tuomas2** [comment]
No, I refer to "snackbar" (https://material.io/components/snackbars/android) (which was in v3.3) which I removed at some point (forgot this ticket).
